"""Fortran codegen — LEGO hello world.

Uses LEGO to derive row-major index expressions, renders them as Fortran,
writes a complete program, compiles with gfortran, and runs it.

Requires: module load gcc  (includes gfortran)
"""

import os
import subprocess
import tempfile
import sympy as sp

from lego.core import OrderBy, Row
from lego.fortran_printer import LEGOFortranCodePrinter

# ── Symbolic layout evaluation ───────────────────────────────────────────

M, N = sp.symbols('M N', integer=True, positive=True)
i, j = sp.symbols('i j', integer=True, positive=True)
x = sp.Symbol('x', integer=True, positive=True)

L = OrderBy(Row(M, N)).GroupBy([(M, N)])
forward_expr = L.apply(i, j)
inv_exprs = L.inv(x)

p = LEGOFortranCodePrinter()
forward_code = p.doprint(forward_expr).strip()
inv_i_code = p.doprint(inv_exprs[0]).strip()
inv_j_code = p.doprint(inv_exprs[1]).strip()

print(f"LEGO forward: {forward_expr}  ->  Fortran: {forward_code}")
print(f"LEGO inverse: {inv_exprs}")
print()

# ── Generate complete Fortran program ────────────────────────────────────

fortran_src = f"""\
! Auto-generated by LEGO layout algebra
! Layout: Row-major (M, N)
program lego_layout
  implicit none
  integer :: M, N, i, j, flat, ri, rj
  logical :: pass_all

  M = 4
  N = 8
  pass_all = .true.

  write(*,'(A,I2,A,I2,A)') 'Row-major layout (', M, ' x ', N, ')'
  write(*,'(A8,A8,A8,A12,A8)') 'i', 'j', 'flat', 'inv_i', 'inv_j'
  write(*,'(A44)') '--------------------------------------------'

  do i = 0, M - 1
    do j = 0, N - 1
      flat = {forward_code}
      ri = {inv_i_code.replace('x', 'flat')}
      rj = {inv_j_code.replace('x', 'flat')}
      if (ri /= i .or. rj /= j) then
        pass_all = .false.
        write(*,'(I8,I8,I8,I12,I8,A8)') i, j, flat, ri, rj, '  FAIL'
      else
        write(*,'(I8,I8,I8,I12,I8,A8)') i, j, flat, ri, rj, '  OK'
      end if
    end do
  end do

  if (pass_all) then
    write(*,'(/,A)') 'PASS: All roundtrips match'
  else
    write(*,'(/,A)') 'FAIL: Roundtrip mismatch detected'
    stop 1
  end if
end program lego_layout
"""

# ── Compile and run ──────────────────────────────────────────────────────

with tempfile.TemporaryDirectory() as tmp:
    src_path = os.path.join(tmp, "lego_layout.f90")
    bin_path = os.path.join(tmp, "lego_layout")

    with open(src_path, "w") as f:
        f.write(fortran_src)

    print("--- Generated Fortran source ---")
    print(fortran_src)

    print("--- Compiling with gfortran ---")
    result = subprocess.run(["gfortran", "-O2", src_path, "-o", bin_path],
                            capture_output=True, text=True)
    if result.returncode != 0:
        print("Compilation failed:")
        print(result.stderr)
        exit(1)
    print("Compilation OK")

    print("\\n--- Running ---")
    result = subprocess.run([bin_path], capture_output=True, text=True)
    print(result.stdout)
    if result.returncode != 0:
        print(result.stderr)
        exit(1)
