// RUN: lego-opt %s --lego-vectorize | FileCheck %s

// Tests for outer-loop block args treated as loop-invariant in evalAffine.
// These patterns are generated by @cpu_kernel(grid, tile) from the cpu_dsl.
//
// After `lego-lower + canonicalize + CSE`, the inner loop's index is:
//   %off = arith.shli %tile_id, %c4    (or arith.muli %tile_id, %tile_sz)
//   %idx = arith.addi %off, %local_i
// where %tile_id is the outer scf.for block arg and %local_i is the inner IV.
// evalAffine should classify %idx as coeff=1, invariant=%off → Unit stride.

// ---------------------------------------------------------------------------
// Test 1: SAXPY with outer tile loop (cpu_kernel f32 pattern).
// @cpu_kernel(grid=(N,), tile=(16,)) generates:
//   outer: for tile_id in 0..N/16
//     inner: for local_i in 0..16
//       idx = tile_id * 16 + local_i  (= shli tile_id, 4 + local_i after CSE)
//       Y[idx] = a * X[idx] + Y[idx]
//
// For f32, AVX-512 L = 64/4 = 16. tile size == L → fully vectorized inner loop.
// CHECK-LABEL: func.func @cpu_kernel_saxpy_f32
// CHECK: vector.transfer_read {{.*}} : memref<?xf32>, vector<16xf32>
// CHECK: vector.transfer_write {{.*}} : vector<16xf32>, memref<?xf32>
func.func @cpu_kernel_saxpy_f32(%a: f32, %X: memref<?xf32>, %Y: memref<?xf32>,
                                 %num_tiles: index) {
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c16 = arith.constant 16 : index
  scf.for %tile_id = %c0 to %num_tiles step %c1 {
    scf.for %local_i = %c0 to %c16 step %c1 {
      // idx = tile_id * 16 + local_i  (strength-reduced by CSE to shli + addi)
      %off = arith.muli %tile_id, %c16 : index
      %idx = arith.addi %off, %local_i : index
      %xi = memref.load %X[%idx] : memref<?xf32>
      %yi = memref.load %Y[%idx] : memref<?xf32>
      %p  = arith.mulf %a, %xi : f32
      %s  = arith.addf %p, %yi : f32
      memref.store %s, %Y[%idx] : memref<?xf32>
    }
  }
  return
}

// -----

// ---------------------------------------------------------------------------
// Test 2: SAXPY with outer tile loop using shli (strength-reduced form).
// Same pattern as Test 1, but using arith.shli (the CSE output form for
// tile_size == power of 2, e.g. tile_size=16 → shli by 4).
// CHECK-LABEL: func.func @cpu_kernel_saxpy_shli
// CHECK: vector.transfer_read {{.*}} : memref<?xf32>, vector<16xf32>
// CHECK: vector.transfer_write {{.*}} : vector<16xf32>, memref<?xf32>
func.func @cpu_kernel_saxpy_shli(%a: f32, %X: memref<?xf32>, %Y: memref<?xf32>,
                                  %num_tiles: index) {
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c16 = arith.constant 16 : index
  %c4  = arith.constant 4 : index
  scf.for %tile_id = %c0 to %num_tiles step %c1 {
    scf.for %local_i = %c0 to %c16 step %c1 {
      %off = arith.shli %tile_id, %c4 : index
      %idx = arith.addi %off, %local_i : index
      %xi = memref.load %X[%idx] : memref<?xf32>
      %yi = memref.load %Y[%idx] : memref<?xf32>
      %p  = arith.mulf %a, %xi : f32
      %s  = arith.addf %p, %yi : f32
      memref.store %s, %Y[%idx] : memref<?xf32>
    }
  }
  return
}

// -----

// ---------------------------------------------------------------------------
// Test 3: Vec-add with outer tile loop, f64.
// L = 64/8 = 8 for f64; tile size 8 → fully vectorized.
// CHECK-LABEL: func.func @cpu_kernel_vecadd_f64
// CHECK: vector.transfer_read {{.*}} : memref<?xf64>, vector<8xf64>
// CHECK: vector.transfer_write {{.*}} : vector<8xf64>, memref<?xf64>
func.func @cpu_kernel_vecadd_f64(%A: memref<?xf64>, %B: memref<?xf64>, %C: memref<?xf64>,
                                  %num_tiles: index) {
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c8  = arith.constant 8 : index
  scf.for %tile_id = %c0 to %num_tiles step %c1 {
    scf.for %local_i = %c0 to %c8 step %c1 {
      %off = arith.muli %tile_id, %c8 : index
      %idx = arith.addi %off, %local_i : index
      %ai = memref.load %A[%idx] : memref<?xf64>
      %bi = memref.load %B[%idx] : memref<?xf64>
      %s  = arith.addf %ai, %bi : f64
      memref.store %s, %C[%idx] : memref<?xf64>
    }
  }
  return
}

// -----

// ---------------------------------------------------------------------------
// Test 4: Broadcast scalar arg (function argument %a) with outer-tile pattern.
// Function args are also treated as loop-invariant block args (they have no
// defining op). %a should broadcast to vector<16xf32>.
// CHECK-LABEL: func.func @cpu_kernel_broadcast_funcarg
// CHECK: vector.broadcast {{.*}} : f32 to vector<16xf32>
// CHECK: vector.transfer_read {{.*}} : memref<?xf32>, vector<16xf32>
// CHECK: vector.transfer_write {{.*}} : vector<16xf32>, memref<?xf32>
func.func @cpu_kernel_broadcast_funcarg(%scale: f32, %A: memref<?xf32>, %B: memref<?xf32>,
                                         %num_tiles: index) {
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c16 = arith.constant 16 : index
  scf.for %tile_id = %c0 to %num_tiles step %c1 {
    scf.for %local_i = %c0 to %c16 step %c1 {
      %off = arith.muli %tile_id, %c16 : index
      %idx = arith.addi %off, %local_i : index
      %v = memref.load %A[%idx] : memref<?xf32>
      %s = arith.mulf %scale, %v : f32
      memref.store %s, %B[%idx] : memref<?xf32>
    }
  }
  return
}
