"""C++ codegen — LEGO hello world.

Uses LEGO to derive row-major index expressions, renders them as C++ code,
writes a complete program, compiles with g++, and runs it.

Requires: module load gcc
"""

import os
import subprocess
import tempfile
import sympy as sp

from lego.core import OrderBy, Row
from lego.cxx_printer import LEGOCXXCodePrinter

# ── Symbolic layout evaluation ───────────────────────────────────────────

M, N = sp.symbols('M N', integer=True, positive=True)
i, j = sp.symbols('i j', integer=True, positive=True)
x = sp.Symbol('x', integer=True, positive=True)

L = OrderBy(Row(M, N)).GroupBy([(M, N)])
forward_expr = L.apply(i, j)
inv_exprs = L.inv(x)

p = LEGOCXXCodePrinter()
forward_code = p.doprint(forward_expr)
inv_i_code = p.doprint(inv_exprs[0])
inv_j_code = p.doprint(inv_exprs[1])

print(f"LEGO forward: {forward_expr}  ->  C++: {forward_code}")
print(f"LEGO inverse: {inv_exprs}")
print()

# ── Generate complete C++ program ────────────────────────────────────────

cxx_src = f"""\
// Auto-generated by LEGO layout algebra
// Layout: Row-major (M, N)
#include <cstdio>
#include <cstdlib>

long row_major_index(long i, long j, long /*M*/, long N) {{
    return {forward_code};
}}

void row_major_inverse(long x, long /*M*/, long N, long &i_out, long &j_out) {{
    i_out = {inv_i_code};
    j_out = {inv_j_code};
}}

int main() {{
    const long M = 4, N = 8;
    std::printf("Row-major layout (%ld x %ld)\\n", M, N);
    std::printf("%-8s %-8s %-8s %-12s %-8s\\n", "i", "j", "flat", "inv_i", "inv_j");
    std::printf("--------------------------------------------\\n");

    bool pass = true;
    for (long i = 0; i < M; ++i) {{
        for (long j = 0; j < N; ++j) {{
            long flat = row_major_index(i, j, M, N);
            long ri, rj;
            row_major_inverse(flat, M, N, ri, rj);
            bool ok = (ri == i && rj == j);
            if (!ok) pass = false;
            std::printf("%-8ld %-8ld %-8ld %-12ld %-8ld %s\\n",
                        i, j, flat, ri, rj, ok ? "OK" : "FAIL");
        }}
    }}
    if (pass) {{
        std::printf("\\nPASS: All roundtrips match\\n");
        return 0;
    }} else {{
        std::printf("\\nFAIL: Roundtrip mismatch detected\\n");
        return 1;
    }}
}}
"""

# ── Compile and run ──────────────────────────────────────────────────────

with tempfile.TemporaryDirectory() as tmp:
    src_path = os.path.join(tmp, "lego_layout.cpp")
    bin_path = os.path.join(tmp, "lego_layout")

    with open(src_path, "w") as f:
        f.write(cxx_src)

    print("--- Generated C++ source ---")
    print(cxx_src)

    print("--- Compiling with g++ ---")
    result = subprocess.run(["g++", "-std=c++17", "-O2", src_path, "-o", bin_path],
                            capture_output=True, text=True)
    if result.returncode != 0:
        print("Compilation failed:")
        print(result.stderr)
        exit(1)
    print("Compilation OK")

    print("\n--- Running ---")
    result = subprocess.run([bin_path], capture_output=True, text=True)
    print(result.stdout)
    if result.returncode != 0:
        print(result.stderr)
        exit(1)
