"""JavaScript codegen — LEGO hello world.

Uses LEGO to derive row-major index expressions, renders them as JavaScript,
writes a complete Node.js script, and runs it.

Requires: module load nodejs
"""

import os
import subprocess
import tempfile
import sympy as sp

from lego.core import OrderBy, Row
from lego.js_printer import LEGOJSCodePrinter

# ── Symbolic layout evaluation ───────────────────────────────────────────

M, N = sp.symbols('M N', integer=True, positive=True)
i, j = sp.symbols('i j', integer=True, positive=True)
x = sp.Symbol('x', integer=True, positive=True)

L = OrderBy(Row(M, N)).GroupBy([(M, N)])
forward_expr = L.apply(i, j)
inv_exprs = L.inv(x)

p = LEGOJSCodePrinter()
forward_code = p.doprint(forward_expr)
inv_i_code = p.doprint(inv_exprs[0])
inv_j_code = p.doprint(inv_exprs[1])

print(f"LEGO forward: {forward_expr}  ->  JS: {forward_code}")
print(f"LEGO inverse: {inv_exprs}")
print()

# ── Generate complete JavaScript program ─────────────────────────────────

js_src = f"""\
// Auto-generated by LEGO layout algebra
// Layout: Row-major (M, N)

function rowMajorIndex(i, j, M, N) {{
    return {forward_code};
}}

function rowMajorInverse(x, M, N) {{
    const i_out = {inv_i_code};
    const j_out = {inv_j_code};
    return [i_out, j_out];
}}

const M = 4, N = 8;
console.log(`Row-major layout (${{M}} x ${{N}})`);
console.log("i".padEnd(8) + "j".padEnd(8) + "flat".padEnd(8) +
            "inv_i".padEnd(12) + "inv_j".padEnd(8));
console.log("-".repeat(44));

let pass = true;
for (let i = 0; i < M; i++) {{
    for (let j = 0; j < N; j++) {{
        const flat = rowMajorIndex(i, j, M, N);
        const [ri, rj] = rowMajorInverse(flat, M, N);
        const ok = (ri === i && rj === j);
        if (!ok) pass = false;
        console.log(
            String(i).padEnd(8) + String(j).padEnd(8) +
            String(flat).padEnd(8) + String(ri).padEnd(12) +
            String(rj).padEnd(8) + (ok ? "OK" : "FAIL")
        );
    }}
}}

if (pass) {{
    console.log("\\nPASS: All roundtrips match");
}} else {{
    console.log("\\nFAIL: Roundtrip mismatch detected");
    process.exit(1);
}}
"""

# ── Run ──────────────────────────────────────────────────────────────────

with tempfile.TemporaryDirectory() as tmp:
    src_path = os.path.join(tmp, "lego_layout.js")

    with open(src_path, "w") as f:
        f.write(js_src)

    print("--- Generated JavaScript source ---")
    print(js_src)

    print("--- Running with node ---")
    result = subprocess.run(["node", src_path], capture_output=True, text=True)
    print(result.stdout)
    if result.returncode != 0:
        print(result.stderr)
        exit(1)
