
# Autogenerated by mlir-tblgen; don't manually edit.

from ._ods_common import _cext as _ods_cext
from ._ods_common import (
    equally_sized_accessor as _ods_equally_sized_accessor,
    get_default_loc_context as _ods_get_default_loc_context,
    get_op_results_or_values as _get_op_results_or_values,
    segmented_accessor as _ods_segmented_accessor,
)
_ods_ir = _ods_cext.ir
_ods_cext.globals.register_traceback_file_exclusion(__file__)

import builtins
from typing import Sequence as _Sequence, Union as _Union, Optional as _Optional


@_ods_cext.register_dialect
class _Dialect(_ods_ir.Dialect):
  DIALECT_NAMESPACE = "lego"

@_ods_cext.register_operation(_Dialect)
class ApplyInverseOp(_ods_ir.OpView):
  r"""
  Given a layout and a flat index, returns the original multi-dimensional indices.
  This corresponds to `layout.inv(flat_idx)`.
  """

  OPERATION_NAME = "lego.apply_inverse"

  _ODS_REGIONS = (0, True)

  def __init__(self, indices, layout, flat_index, *, loc=None, ip=None):
    operands = []
    attributes = {}
    regions = None
    operands.append(layout)
    operands.append(flat_index)
    _ods_context = _ods_get_default_loc_context(loc)
    results = []
    results.extend(indices)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def layout(self) -> _ods_ir.Value:
    return self.operation.operands[0]

  @builtins.property
  def flat_index(self) -> _ods_ir.Value[_ods_ir.IndexType]:
    return self.operation.operands[1]

  @builtins.property
  def indices(self) -> _ods_ir.OpResultList:
    _ods_variadic_group_length = len(self.operation.results) - 1 + 1
    return self.operation.results[0:0 + _ods_variadic_group_length]

@_ods_cext.register_op_adaptor(ApplyInverseOp)
class ApplyInverseOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "lego.apply_inverse"

  @builtins.property
  def layout(self) -> _ods_ir.Value:
    return self.operands[0]

  @builtins.property
  def flat_index(self) -> _ods_ir.Value[_ods_ir.IndexType]:
    return self.operands[1]

def apply_inverse(indices, layout, flat_index, *, loc=None, ip=None) -> _Union[_ods_ir.OpResult, _ods_ir.OpResultList, ApplyInverseOp]:
  op = ApplyInverseOp(indices=indices, layout=layout, flat_index=flat_index, loc=loc, ip=ip); results = op.results
  return results if len(results) > 1 else (results[0] if len(results) == 1 else op)

@_ods_cext.register_operation(_Dialect)
class ApplyOp(_ods_ir.OpView):
  r"""
  Given a layout and a set of indices, returns the flattened index.
  This corresponds to `layout.apply(idx)`.
  """

  OPERATION_NAME = "lego.apply"

  _ODS_REGIONS = (0, True)

  def __init__(self, flat_index, layout, indices, *, loc=None, ip=None):
    operands = []
    attributes = {}
    regions = None
    operands.append(layout)
    operands.extend(_get_op_results_or_values(indices))
    _ods_context = _ods_get_default_loc_context(loc)
    results = []
    results.append(flat_index)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def layout(self) -> _ods_ir.Value:
    return self.operation.operands[0]

  @builtins.property
  def indices(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operation.operands) - 2 + 1
    return self.operation.operands[1:1 + _ods_variadic_group_length]

  @builtins.property
  def flat_index(self) -> _ods_ir.OpResult[_ods_ir.IndexType]:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(ApplyOp)
class ApplyOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "lego.apply"

  @builtins.property
  def layout(self) -> _ods_ir.Value:
    return self.operands[0]

  @builtins.property
  def indices(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operands) - 2 + 1
    return self.operands[1:1 + _ods_variadic_group_length]

def apply(flat_index, layout, indices, *, loc=None, ip=None) -> _ods_ir.OpResult:
  return ApplyOp(flat_index=flat_index, layout=layout, indices=indices, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class AssertApplyBoundsOp(_ods_ir.OpView):
  OPERATION_NAME = "lego.assert_apply_bounds"

  _ODS_REGIONS = (0, True)

  def __init__(self, layout, indices, *, loc=None, ip=None):
    operands = []
    attributes = {}
    regions = None
    operands.append(layout)
    operands.extend(_get_op_results_or_values(indices))
    _ods_context = _ods_get_default_loc_context(loc)
    results = []
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def layout(self) -> _ods_ir.Value:
    return self.operation.operands[0]

  @builtins.property
  def indices(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operation.operands) - 2 + 1
    return self.operation.operands[1:1 + _ods_variadic_group_length]

@_ods_cext.register_op_adaptor(AssertApplyBoundsOp)
class AssertApplyBoundsOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "lego.assert_apply_bounds"

  @builtins.property
  def layout(self) -> _ods_ir.Value:
    return self.operands[0]

  @builtins.property
  def indices(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operands) - 2 + 1
    return self.operands[1:1 + _ods_variadic_group_length]

def assert_apply_bounds(layout, indices, *, loc=None, ip=None) -> AssertApplyBoundsOp:
  return AssertApplyBoundsOp(layout=layout, indices=indices, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class AssertInvBoundsOp(_ods_ir.OpView):
  OPERATION_NAME = "lego.assert_inv_bounds"

  _ODS_REGIONS = (0, True)

  def __init__(self, layout, flat_index, *, loc=None, ip=None):
    operands = []
    attributes = {}
    regions = None
    operands.append(layout)
    operands.append(flat_index)
    _ods_context = _ods_get_default_loc_context(loc)
    results = []
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def layout(self) -> _ods_ir.Value:
    return self.operation.operands[0]

  @builtins.property
  def flat_index(self) -> _ods_ir.Value[_ods_ir.IndexType]:
    return self.operation.operands[1]

@_ods_cext.register_op_adaptor(AssertInvBoundsOp)
class AssertInvBoundsOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "lego.assert_inv_bounds"

  @builtins.property
  def layout(self) -> _ods_ir.Value:
    return self.operands[0]

  @builtins.property
  def flat_index(self) -> _ods_ir.Value[_ods_ir.IndexType]:
    return self.operands[1]

def assert_inv_bounds(layout, flat_index, *, loc=None, ip=None) -> AssertInvBoundsOp:
  return AssertInvBoundsOp(layout=layout, flat_index=flat_index, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class AssumeBoundsOp(_ods_ir.OpView):
  r"""
  A sugar operation that asserts the value is bounded by optional lower and/or upper bounds.
  Lower bounded (inclusive) and upper bounded (exclusive).
  Lowered to `lego.assume` and `arith.cmpi` during normalization.
  """

  OPERATION_NAME = "lego.assume_bounds"

  _ODS_OPERAND_SEGMENTS = [1,0,0,]

  _ODS_REGIONS = (0, True)

  def __init__(self, value, *, lb=None, ub=None, loc=None, ip=None):
    operands = []
    attributes = {}
    regions = None
    operands.append(value)
    operands.append(lb)
    operands.append(ub)
    _ods_context = _ods_get_default_loc_context(loc)
    results = []
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def value(self) -> _ods_ir.Value[_ods_ir.IndexType]:
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 0)
    return operand_range[0]

  @builtins.property
  def lb(self) -> _Optional[_ods_ir.Value[_ods_ir.IndexType]]:
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 1)
    return operand_range[0] if len(operand_range) > 0 else None

  @builtins.property
  def ub(self) -> _Optional[_ods_ir.Value[_ods_ir.IndexType]]:
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 2)
    return operand_range[0] if len(operand_range) > 0 else None

@_ods_cext.register_op_adaptor(AssumeBoundsOp)
class AssumeBoundsOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "lego.assume_bounds"

  @builtins.property
  def value(self) -> _ods_ir.Value[_ods_ir.IndexType]:
    operand_range = _ods_segmented_accessor(
         self.operands,
         self.attributes["operandSegmentSizes"], 0)
    return operand_range[0]

  @builtins.property
  def lb(self) -> _Optional[_ods_ir.Value[_ods_ir.IndexType]]:
    operand_range = _ods_segmented_accessor(
         self.operands,
         self.attributes["operandSegmentSizes"], 1)
    return operand_range[0] if len(operand_range) > 0 else None

  @builtins.property
  def ub(self) -> _Optional[_ods_ir.Value[_ods_ir.IndexType]]:
    operand_range = _ods_segmented_accessor(
         self.operands,
         self.attributes["operandSegmentSizes"], 2)
    return operand_range[0] if len(operand_range) > 0 else None

def assume_bounds(value, *, lb=None, ub=None, loc=None, ip=None) -> AssumeBoundsOp:
  return AssumeBoundsOp(value=value, lb=lb, ub=ub, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class AssumeOp(_ods_ir.OpView):
  r"""
  `lego.assume` asserts that a given boolean condition always holds true at runtime.
  The verifier will use this as an axiom.
  """

  OPERATION_NAME = "lego.assume"

  _ODS_REGIONS = (0, True)

  def __init__(self, condition, *, loc=None, ip=None):
    operands = []
    attributes = {}
    regions = None
    operands.append(condition)
    _ods_context = _ods_get_default_loc_context(loc)
    results = []
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def condition(self) -> _ods_ir.Value[_ods_ir.IntegerType]:
    return self.operation.operands[0]

@_ods_cext.register_op_adaptor(AssumeOp)
class AssumeOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "lego.assume"

  @builtins.property
  def condition(self) -> _ods_ir.Value[_ods_ir.IntegerType]:
    return self.operands[0]

def assume(condition, *, loc=None, ip=None) -> AssumeOp:
  return AssumeOp(condition=condition, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class CastViewOp(_ods_ir.OpView):
  r"""
  Wraps a standard `memref` with a `lego.layout`, creating a `!lego.view`.
  This operation does not copy data; it merely provides a logical view.
  """

  OPERATION_NAME = "lego.cast_view"

  _ODS_REGIONS = (0, True)

  def __init__(self, view, memref, layout, *, loc=None, ip=None):
    operands = []
    attributes = {}
    regions = None
    operands.append(memref)
    operands.append(layout)
    _ods_context = _ods_get_default_loc_context(loc)
    results = []
    results.append(view)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def memref(self) -> _ods_ir.Value[_ods_ir.MemRefType]:
    return self.operation.operands[0]

  @builtins.property
  def layout(self) -> _ods_ir.Value:
    return self.operation.operands[1]

  @builtins.property
  def view(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(CastViewOp)
class CastViewOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "lego.cast_view"

  @builtins.property
  def memref(self) -> _ods_ir.Value[_ods_ir.MemRefType]:
    return self.operands[0]

  @builtins.property
  def layout(self) -> _ods_ir.Value:
    return self.operands[1]

def cast_view(view, memref, layout, *, loc=None, ip=None) -> _ods_ir.OpResult:
  return CastViewOp(view=view, memref=memref, layout=layout, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class ColOp(_ods_ir.OpView):
  r"""
  Col(*dims) = RegP(dims, [d-1, d-2, ..., 0]).
  Sugar for RegP with reversed identity permutation.
  """

  OPERATION_NAME = "lego.col"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, dims, *, loc=None, ip=None):
    operands = []
    attributes = {}
    regions = None
    operands.extend(_get_op_results_or_values(dims))
    _ods_context = _ods_get_default_loc_context(loc)
    results = []
    results.append(result)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def dims(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operation.operands) - 1 + 1
    return self.operation.operands[0:0 + _ods_variadic_group_length]

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(ColOp)
class ColOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "lego.col"

  @builtins.property
  def dims(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operands) - 1 + 1
    return self.operands[0:0 + _ods_variadic_group_length]

def col(result, dims, *, loc=None, ip=None) -> _ods_ir.OpResult:
  return ColOp(result=result, dims=dims, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class GenPOp(_ods_ir.OpView):
  r"""
  For complex layouts like `antidiag` where the transformation cannot be expressed
  by a simple permutation. Contains two regions:
  
  - `apply` region: takes N-D indices as block args, yields a single flat index
  - `inv` region (optional): takes a flat index as block arg, yields N-D indices
  
  Both regions are terminated with `lego.yield`.
  
  Example:
  ```mlir
  %layout = lego.gen_p [4, 4]
    apply {
    ^bb0(%i: index, %j: index):
      %sum = arith.addi %i, %j : index
      lego.yield %sum : index
    }
    inv {
    ^bb0(%flat: index):
      %c4 = arith.constant 4 : index
      %i = arith.divui %flat, %c4 : index
      %j = arith.remui %flat, %c4 : index
      lego.yield %i, %j : index, index
    } : !lego.layout
  ```
  """

  OPERATION_NAME = "lego.gen_p"

  _ODS_REGIONS = (2, True)

  def __init__(self, result, dims, *, loc=None, ip=None):
    operands = []
    attributes = {}
    regions = None
    operands.extend(_get_op_results_or_values(dims))
    _ods_context = _ods_get_default_loc_context(loc)
    results = []
    results.append(result)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def dims(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operation.operands) - 1 + 1
    return self.operation.operands[0:0 + _ods_variadic_group_length]

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

  @builtins.property
  def body(self) -> _ods_ir.Region:
    return self.regions[0]

  @builtins.property
  def inv_body(self) -> _ods_ir.Region:
    return self.regions[1]

@_ods_cext.register_op_adaptor(GenPOp)
class GenPOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "lego.gen_p"

  @builtins.property
  def dims(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operands) - 1 + 1
    return self.operands[0:0 + _ods_variadic_group_length]

def gen_p(result, dims, *, loc=None, ip=None) -> _ods_ir.OpResult:
  return GenPOp(result=result, dims=dims, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class GroupByOp(_ods_ir.OpView):
  r"""
  Groups the input dimensions according to `group_dims` and then applies the
  sequence of layout objects. During apply, objects are iterated in reverse:
  for each object, unflatten the current flat index into the object's dims,
  then apply the object. During inv, objects are iterated forward.
  
  Example: `lego.group_by [4, 5](%ob1, %ob2) : !lego.layout`
  """

  OPERATION_NAME = "lego.group_by"

  _ODS_OPERAND_SEGMENTS = [-1,-1,]

  _ODS_REGIONS = (0, True)

  def __init__(self, result, group_dims, objects, *, loc=None, ip=None):
    operands = []
    attributes = {}
    regions = None
    operands.append(_get_op_results_or_values(group_dims))
    operands.append(_get_op_results_or_values(objects))
    _ods_context = _ods_get_default_loc_context(loc)
    results = []
    results.append(result)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def group_dims(self) -> _ods_ir.OpOperandList:
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 0)
    return operand_range

  @builtins.property
  def objects(self) -> _ods_ir.OpOperandList:
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 1)
    return operand_range

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(GroupByOp)
class GroupByOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "lego.group_by"

  @builtins.property
  def group_dims(self) -> _ods_ir.OpOperandList:
    operand_range = _ods_segmented_accessor(
         self.operands,
         self.attributes["operandSegmentSizes"], 0)
    return operand_range

  @builtins.property
  def objects(self) -> _ods_ir.OpOperandList:
    operand_range = _ods_segmented_accessor(
         self.operands,
         self.attributes["operandSegmentSizes"], 1)
    return operand_range

def group_by(result, group_dims, objects, *, loc=None, ip=None) -> _ods_ir.OpResult:
  return GroupByOp(result=result, group_dims=group_dims, objects=objects, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class LoadOp(_ods_ir.OpView):
  r"""
  Loads a value from the view at the specified logical indices.
  The indices are mapped to a flat index via the view's layout.
  """

  OPERATION_NAME = "lego.load"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, view, indices, *, loc=None, ip=None):
    operands = []
    attributes = {}
    regions = None
    operands.append(view)
    operands.extend(_get_op_results_or_values(indices))
    _ods_context = _ods_get_default_loc_context(loc)
    results = []
    results.append(result)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def view(self) -> _ods_ir.Value:
    return self.operation.operands[0]

  @builtins.property
  def indices(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operation.operands) - 2 + 1
    return self.operation.operands[1:1 + _ods_variadic_group_length]

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(LoadOp)
class LoadOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "lego.load"

  @builtins.property
  def view(self) -> _ods_ir.Value:
    return self.operands[0]

  @builtins.property
  def indices(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operands) - 2 + 1
    return self.operands[1:1 + _ods_variadic_group_length]

def load(result, view, indices, *, loc=None, ip=None) -> _ods_ir.OpResult:
  return LoadOp(result=result, view=view, indices=indices, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class OrderByOp(_ods_ir.OpView):
  r"""
  Represents a layout composed of a sequence of permutation blocks.
  Each block consumes a subset of the input indices and produces a flat sub-index.
  The final flat index is computed by combining sub-indices in mixed-radix form.
  
  Example: `lego.order_by(%l1, %l2) : !lego.layout`
  """

  OPERATION_NAME = "lego.order_by"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, perms, *, loc=None, ip=None):
    operands = []
    attributes = {}
    regions = None
    operands.extend(_get_op_results_or_values(perms))
    _ods_context = _ods_get_default_loc_context(loc)
    results = []
    results.append(result)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def perms(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operation.operands) - 1 + 1
    return self.operation.operands[0:0 + _ods_variadic_group_length]

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(OrderByOp)
class OrderByOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "lego.order_by"

  @builtins.property
  def perms(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operands) - 1 + 1
    return self.operands[0:0 + _ods_variadic_group_length]

def order_by(result, perms, *, loc=None, ip=None) -> _ods_ir.OpResult:
  return OrderByOp(result=result, perms=perms, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class RegPOp(_ods_ir.OpView):
  r"""
  Creates a layout block defined by a permutation vector.
  Equivalent to reordering the dimensions according to `perm`.
  """

  OPERATION_NAME = "lego.reg_p"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, perm, dims, *, loc=None, ip=None):
    operands = []
    attributes = {}
    regions = None
    operands.extend(_get_op_results_or_values(dims))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["perm"] = (perm if (
    isinstance(perm, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('I64ArrayAttr')) else
      _ods_ir.AttrBuilder.get('I64ArrayAttr')(perm, context=_ods_context))
    results = []
    results.append(result)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def dims(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operation.operands) - 1 + 1
    return self.operation.operands[0:0 + _ods_variadic_group_length]

  @builtins.property
  def perm(self) -> _ods_ir.ArrayAttr:
    return self.operation.attributes["perm"]

  @perm.setter
  def perm(self, value: _ods_ir.ArrayAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["perm"] = value

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(RegPOp)
class RegPOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "lego.reg_p"

  @builtins.property
  def dims(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operands) - 1 + 1
    return self.operands[0:0 + _ods_variadic_group_length]

  @builtins.property
  def perm(self) -> _ods_ir.ArrayAttr:
    return self.attributes["perm"]

def reg_p(result, perm, dims, *, loc=None, ip=None) -> _ods_ir.OpResult:
  return RegPOp(result=result, perm=perm, dims=dims, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class RowOp(_ods_ir.OpView):
  r"""
  Row(*dims) = RegP(dims, [0, 1, ..., d-1]).
  Sugar for RegP with identity permutation.
  """

  OPERATION_NAME = "lego.row"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, dims, *, loc=None, ip=None):
    operands = []
    attributes = {}
    regions = None
    operands.extend(_get_op_results_or_values(dims))
    _ods_context = _ods_get_default_loc_context(loc)
    results = []
    results.append(result)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def dims(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operation.operands) - 1 + 1
    return self.operation.operands[0:0 + _ods_variadic_group_length]

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(RowOp)
class RowOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "lego.row"

  @builtins.property
  def dims(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operands) - 1 + 1
    return self.operands[0:0 + _ods_variadic_group_length]

def row(result, dims, *, loc=None, ip=None) -> _ods_ir.OpResult:
  return RowOp(result=result, dims=dims, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class StoreOp(_ods_ir.OpView):
  r"""
  Stores a value into the view at the specified logical indices.
  The indices are mapped to a flat index via the view's layout.
  """

  OPERATION_NAME = "lego.store"

  _ODS_REGIONS = (0, True)

  def __init__(self, value, view, indices, *, loc=None, ip=None):
    operands = []
    attributes = {}
    regions = None
    operands.append(value)
    operands.append(view)
    operands.extend(_get_op_results_or_values(indices))
    _ods_context = _ods_get_default_loc_context(loc)
    results = []
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def value(self) -> _ods_ir.Value:
    return self.operation.operands[0]

  @builtins.property
  def view(self) -> _ods_ir.Value:
    return self.operation.operands[1]

  @builtins.property
  def indices(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operation.operands) - 3 + 1
    return self.operation.operands[2:2 + _ods_variadic_group_length]

@_ods_cext.register_op_adaptor(StoreOp)
class StoreOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "lego.store"

  @builtins.property
  def value(self) -> _ods_ir.Value:
    return self.operands[0]

  @builtins.property
  def view(self) -> _ods_ir.Value:
    return self.operands[1]

  @builtins.property
  def indices(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operands) - 3 + 1
    return self.operands[2:2 + _ods_variadic_group_length]

def store(value, view, indices, *, loc=None, ip=None) -> StoreOp:
  return StoreOp(value=value, view=view, indices=indices, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class TileByOp(_ods_ir.OpView):
  r"""
  Tiles the input OrderBy layout into groups of `d` dimensions each.
  `tile_dims` is a nested list of group dimensions efficiently represented as ArrayAttr containing I64ArrayAttrs.
  `d` is inferred from `len(tile_dims[0])`.
  `q` is inferred from `len(tile_dims)`.
  
  Example: OrderBy(Row(384,384,384)).TileBy([48,48,48], [8,8,8])
  ```mlir
  %r = lego.row [384, 384, 384] : !lego.layout
  %ob = lego.order_by(%r) : !lego.layout
  // d=3, q=2 inferred from nested list
  %tb = lego.tile_by %ob tile_dims [[48, 48, 48], [8, 8, 8]] : !lego.layout
  ```
  """

  OPERATION_NAME = "lego.tile_by"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, input, tile_dims, tile_shape, *, loc=None, ip=None):
    operands = []
    attributes = {}
    regions = None
    operands.append(input)
    operands.extend(_get_op_results_or_values(tile_dims))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["tile_shape"] = (tile_shape if (
    isinstance(tile_shape, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('I64ArrayAttr')) else
      _ods_ir.AttrBuilder.get('I64ArrayAttr')(tile_shape, context=_ods_context))
    results = []
    results.append(result)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def input(self) -> _ods_ir.Value:
    return self.operation.operands[0]

  @builtins.property
  def tile_dims(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operation.operands) - 2 + 1
    return self.operation.operands[1:1 + _ods_variadic_group_length]

  @builtins.property
  def tile_shape(self) -> _ods_ir.ArrayAttr:
    return self.operation.attributes["tile_shape"]

  @tile_shape.setter
  def tile_shape(self, value: _ods_ir.ArrayAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["tile_shape"] = value

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(TileByOp)
class TileByOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "lego.tile_by"

  @builtins.property
  def input(self) -> _ods_ir.Value:
    return self.operands[0]

  @builtins.property
  def tile_dims(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operands) - 2 + 1
    return self.operands[1:1 + _ods_variadic_group_length]

  @builtins.property
  def tile_shape(self) -> _ods_ir.ArrayAttr:
    return self.attributes["tile_shape"]

def tile_by(result, input, tile_dims, tile_shape, *, loc=None, ip=None) -> _ods_ir.OpResult:
  return TileByOp(result=result, input=input, tile_dims=tile_dims, tile_shape=tile_shape, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class YieldOp(_ods_ir.OpView):
  r"""
  Terminates a region in `lego.gen_p`, yielding the computed flat index.
  """

  OPERATION_NAME = "lego.yield"

  _ODS_REGIONS = (0, True)

  def __init__(self, values, *, loc=None, ip=None):
    operands = []
    attributes = {}
    regions = None
    operands.extend(_get_op_results_or_values(values))
    _ods_context = _ods_get_default_loc_context(loc)
    results = []
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def values(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operation.operands) - 1 + 1
    return self.operation.operands[0:0 + _ods_variadic_group_length]

@_ods_cext.register_op_adaptor(YieldOp)
class YieldOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "lego.yield"

  @builtins.property
  def values(self) -> _ods_ir.OpOperandList:
    _ods_variadic_group_length = len(self.operands) - 1 + 1
    return self.operands[0:0 + _ods_variadic_group_length]

def yield_(values, *, loc=None, ip=None) -> YieldOp:
  return YieldOp(values=values, loc=loc, ip=ip)
