"""CUDA C codegen — LEGO hello world.

Uses LEGO to derive row-major index expressions, renders them as CUDA C,
writes a complete kernel + host program, compiles with nvcc, and runs it.

Requires: module load cuda gcc
"""

import os
import subprocess
import tempfile
import sympy as sp

from lego.core import OrderBy, Row
from lego.cuda_c_printer import LEGOCUDACCodePrinter

# ── Symbolic layout evaluation ───────────────────────────────────────────

M, N = sp.symbols('M N', integer=True, positive=True)
i, j = sp.symbols('i j', integer=True, positive=True)
x = sp.Symbol('x', integer=True, positive=True)

L = OrderBy(Row(M, N)).GroupBy([(M, N)])
forward_expr = L.apply(i, j)
inv_exprs = L.inv(x)

p = LEGOCUDACCodePrinter()
forward_code = p.doprint(forward_expr)
inv_i_code = p.doprint(inv_exprs[0])
inv_j_code = p.doprint(inv_exprs[1])

print(f"LEGO forward: {forward_expr}  ->  CUDA C: {forward_code}")
print(f"LEGO inverse: {inv_exprs}")
print()

# ── Generate complete CUDA program ───────────────────────────────────────

cuda_src = f"""\
// Auto-generated by LEGO layout algebra
// Layout: Row-major (M, N) — verified on GPU via roundtrip
#include <cstdio>
#include <cstdlib>

__device__ long row_major_index(long i, long j, long M, long N) {{
    return {forward_code};
}}

__device__ void row_major_inverse(long x, long M, long N, long &i_out, long &j_out) {{
    i_out = {inv_i_code};
    j_out = {inv_j_code};
}}

__global__ void verify_roundtrip(int *results, long M, long N) {{
    long tid = blockIdx.x * blockDim.x + threadIdx.x;
    if (tid >= M * N) return;

    long i = tid / N;
    long j = tid % N;

    // Forward: (i, j) -> flat
    long flat = row_major_index(i, j, M, N);
    // Inverse: flat -> (ri, rj)
    long ri, rj;
    row_major_inverse(flat, M, N, ri, rj);

    // 1 if roundtrip matches, 0 otherwise
    results[tid] = (ri == i && rj == j) ? 1 : 0;
}}

int main() {{
    const long M = 4, N = 8;
    const long total = M * N;

    int *d_results, *h_results;
    h_results = (int *)malloc(total * sizeof(int));
    cudaMalloc(&d_results, total * sizeof(int));

    int threads = 256;
    int blocks = (total + threads - 1) / threads;
    verify_roundtrip<<<blocks, threads>>>(d_results, M, N);
    cudaMemcpy(h_results, d_results, total * sizeof(int), cudaMemcpyDeviceToHost);

    printf("Row-major layout (%ld x %ld) — GPU roundtrip verification\\n", M, N);

    bool pass = true;
    for (long idx = 0; idx < total; ++idx) {{
        if (h_results[idx] != 1) {{
            long i = idx / N, j = idx % N;
            printf("FAIL at (%ld, %ld)\\n", i, j);
            pass = false;
        }}
    }}

    if (pass)
        printf("PASS: All %ld roundtrips match on GPU\\n", total);
    else {{
        printf("FAIL: Roundtrip mismatch detected\\n");
        free(h_results);
        cudaFree(d_results);
        return 1;
    }}

    free(h_results);
    cudaFree(d_results);
    return 0;
}}
"""

# ── Compile and run ──────────────────────────────────────────────────────

with tempfile.TemporaryDirectory() as tmp:
    src_path = os.path.join(tmp, "lego_layout.cu")
    bin_path = os.path.join(tmp, "lego_layout")

    with open(src_path, "w") as f:
        f.write(cuda_src)

    print("--- Generated CUDA C source ---")
    print(cuda_src)

    print("--- Compiling with nvcc ---")
    result = subprocess.run(["nvcc", "-O2", src_path, "-o", bin_path],
                            capture_output=True, text=True)
    if result.returncode != 0:
        print("Compilation failed:")
        print(result.stderr)
        exit(1)
    print("Compilation OK")

    print("\n--- Running on GPU ---")
    result = subprocess.run([bin_path], capture_output=True, text=True)
    print(result.stdout)
    if result.returncode != 0:
        print(result.stderr)
        exit(1)
