"""GLSL codegen — LEGO hello world.

Uses LEGO to derive row-major index expressions and renders them as GLSL
compute shader source.  Since GLSL requires a GPU driver and graphics context
to compile/run, this example generates and prints the shader source only.

No special modules required (pure source generation).
"""

import sympy as sp

from lego.core import OrderBy, Row, Col
from lego.glsl_printer import LEGOGLSLCodePrinter

# ── Symbolic layout evaluation ───────────────────────────────────────────

M, N = sp.symbols('M N', integer=True, positive=True)
i, j = sp.symbols('i j', integer=True, positive=True)
x = sp.Symbol('x', integer=True, positive=True)

# Row-major layout
L_row = OrderBy(Row(M, N)).GroupBy([(M, N)])
fwd_row = L_row.apply(i, j)
inv_row = L_row.inv(x)

# Column-major layout
L_col = OrderBy(Col(M, N)).GroupBy([(M, N)])
fwd_col = L_col.apply(i, j)
inv_col = L_col.inv(x)

p = LEGOGLSLCodePrinter()

print("LEGO Row-major forward:", fwd_row)
print("LEGO Row-major inverse:", inv_row)
print("LEGO Col-major forward:", fwd_col)
print("LEGO Col-major inverse:", inv_col)
print()

# ── Generate GLSL compute shader ─────────────────────────────────────────

glsl_src = f"""\
#version 450
// Auto-generated by LEGO layout algebra
// Demonstrates row-major and column-major index computations in GLSL

layout(local_size_x = 256) in;

layout(std430, binding = 0) buffer InputBuf  {{ int data_in[];  }};
layout(std430, binding = 1) buffer OutputBuf {{ int data_out[]; }};

uniform int M;
uniform int N;

// Row-major: (i, j) -> flat index
int row_major_index(int i, int j, int M, int N) {{
    return {p.doprint(fwd_row)};
}}

// Row-major inverse: flat -> (i, j)
ivec2 row_major_inverse(int x, int M, int N) {{
    int i_out = {p.doprint(inv_row[0])};
    int j_out = {p.doprint(inv_row[1])};
    return ivec2(i_out, j_out);
}}

// Column-major: (i, j) -> flat index
int col_major_index(int i, int j, int M, int N) {{
    return {p.doprint(fwd_col)};
}}

// Column-major inverse: flat -> (i, j)
ivec2 col_major_inverse(int x, int M, int N) {{
    int i_out = {p.doprint(inv_col[0])};
    int j_out = {p.doprint(inv_col[1])};
    return ivec2(i_out, j_out);
}}

void main() {{
    uint gid = gl_GlobalInvocationID.x;
    if (gid >= uint(M * N)) return;

    // Read data using row-major layout
    ivec2 coords = row_major_inverse(int(gid), M, N);
    int val = data_in[row_major_index(coords.x, coords.y, M, N)];

    // Write data using column-major layout (transpose!)
    int col_idx = col_major_index(coords.x, coords.y, M, N);
    data_out[col_idx] = val;
}}
"""

print("--- Generated GLSL compute shader ---")
print(glsl_src)
print("PASS: GLSL source generated successfully")
print("(To compile: use glslangValidator or embed in a Vulkan/OpenGL application)")
