//===- LegoVectorize.cpp - Layout-agnostic vectorization pass -------------===//
//
// Lowers loops over Lego-derived arith address expressions to MLIR vector
// dialect ops by symbolic stride analysis. Layout-agnostic: operates on
// post-LegoToArith IR (arith + memref + scf).
//
// Phase B Tasks 5-7: stride analysis + strip-mine factor computation.
// Phase B Task 8:    emit vector.transfer_read/write for unit-stride loops.
//
//===----------------------------------------------------------------------===//

#define GEN_PASS_DEF_LEGOVECTORIZEPASS
#include "Lego/Passes.h"

#include "LegoVectorizeUtils.h"

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/Pass/Pass.h"

#include <algorithm>  // std::find
#include <limits>
#include <numeric>  // std::gcd (C++17)

using namespace mlir;

// ---------------------------------------------------------------------------
// Tier-A stride solver implementation
// ---------------------------------------------------------------------------
namespace mlir::lego {

// ---------------------------------------------------------------------------
// Lightweight symbolic integer evaluator.
//
// Represents values as (base_coeff * iv + constant_offset) where:
//   - base_coeff = coefficient of the induction variable
//   - constant   = the constant offset
//   - valid      = false if the expression is non-affine / unknown
//
// This is sufficient for Tier-A: all address expressions generated by
// LegoToArith for 1-D row-major accesses are linear in the loop iv.
// ---------------------------------------------------------------------------
struct AffineVal {
  bool valid = true;     // false → NonAffine (bail out)
  int64_t coeff = 0;     // coefficient of iv
  int64_t constant = 0;  // constant part

  static AffineVal nonAffine() {
    AffineVal v;
    v.valid = false;
    return v;
  }
  static AffineVal constant_val(int64_t c) {
    AffineVal v;
    v.coeff = 0;
    v.constant = c;
    return v;
  }
  static AffineVal iv_val() {
    AffineVal v;
    v.coeff = 1;
    v.constant = 0;
    return v;
  }
};

// Evaluate the index expression `v` symbolically.
// `iv` is the loop induction variable; any other block argument is NonAffine.
// Caches results in `cache` (keyed by Value) to avoid exponential blowup.
static AffineVal evalAffine(Value v, Value iv,
                             llvm::DenseMap<Value, AffineVal> &cache) {
  // Cache hit?
  auto it = cache.find(v);
  if (it != cache.end())
    return it->second;

  AffineVal result;

  // Block argument cases.
  Operation *defOp = v.getDefiningOp();
  if (!defOp) {
    // Block argument: if it's the induction variable, it's iv; otherwise fail.
    result = (v == iv) ? AffineVal::iv_val() : AffineVal::nonAffine();
    cache[v] = result;
    return result;
  }

  // Constant index.
  if (auto cst = dyn_cast<arith::ConstantIndexOp>(defOp)) {
    result = AffineVal::constant_val(cst.value());
    cache[v] = result;
    return result;
  }

  // Generic arith.constant returning index type.
  if (auto cst = dyn_cast<arith::ConstantOp>(defOp)) {
    if (auto iattr = dyn_cast<IntegerAttr>(cst.getValue())) {
      result = AffineVal::constant_val(iattr.getInt());
      cache[v] = result;
      return result;
    }
    result = AffineVal::nonAffine();
    cache[v] = result;
    return result;
  }

  // addi(a, b)  →  (ca+cb)*iv + (ka+kb)
  if (auto add = dyn_cast<arith::AddIOp>(defOp)) {
    auto a = evalAffine(add.getLhs(), iv, cache);
    auto b = evalAffine(add.getRhs(), iv, cache);
    if (!a.valid || !b.valid)
      result = AffineVal::nonAffine();
    else
      result = {true, a.coeff + b.coeff, a.constant + b.constant};
    cache[v] = result;
    return result;
  }

  // subi(a, b)  →  (ca-cb)*iv + (ka-kb)
  if (auto sub = dyn_cast<arith::SubIOp>(defOp)) {
    auto a = evalAffine(sub.getLhs(), iv, cache);
    auto b = evalAffine(sub.getRhs(), iv, cache);
    if (!a.valid || !b.valid)
      result = AffineVal::nonAffine();
    else
      result = {true, a.coeff - b.coeff, a.constant - b.constant};
    cache[v] = result;
    return result;
  }

  // muli(a, constant)  →  ca*constant*iv + ka*constant
  if (auto mul = dyn_cast<arith::MulIOp>(defOp)) {
    auto a = evalAffine(mul.getLhs(), iv, cache);
    auto b = evalAffine(mul.getRhs(), iv, cache);
    if (!a.valid || !b.valid) {
      result = AffineVal::nonAffine();
    } else if (a.coeff == 0) {
      // a is a constant; b may have iv.
      result = {true, a.constant * b.coeff, a.constant * b.constant};
    } else if (b.coeff == 0) {
      // b is a constant; a may have iv.
      result = {true, b.constant * a.coeff, b.constant * a.constant};
    } else {
      // Both have iv → quadratic, not affine.
      result = AffineVal::nonAffine();
    }
    cache[v] = result;
    return result;
  }

  // index_cast (arith.index_cast or arith.index_castui) — treat as identity.
  if (isa<arith::IndexCastOp, arith::IndexCastUIOp>(defOp)) {
    result = evalAffine(defOp->getOperand(0), iv, cache);
    cache[v] = result;
    return result;
  }

  // Anything else → NonAffine.
  result = AffineVal::nonAffine();
  cache[v] = result;
  return result;
}

AccessClassification solveAccessTierA(Operation *memrefOp, Value iv,
                                      int64_t elementBytes) {
  AccessClassification cls;
  cls.elementBytes = elementBytes;

  // Extract the (first) index from a load or store.
  Value addr;
  if (auto load = dyn_cast<memref::LoadOp>(memrefOp)) {
    if (load.getIndices().empty()) return cls;  // scalar — NonAffine
    addr = load.getIndices().front();
  } else if (auto store = dyn_cast<memref::StoreOp>(memrefOp)) {
    if (store.getIndices().empty()) return cls;
    addr = store.getIndices().front();
  } else {
    return cls;
  }

  // Evaluate S(iv) symbolically.
  llvm::DenseMap<Value, AffineVal> cache;
  AffineVal sym = evalAffine(addr, iv, cache);

  if (!sym.valid) {
    cls.kind = AccessKind::NonAffine;
    return cls;
  }

  // The per-step difference is S(iv+1) - S(iv) = coeff (the coefficient of iv).
  // (S(iv+1) = coeff*(iv+1) + constant = coeff*iv + coeff + constant)
  // diff = S(iv+1) - S(iv) = coeff.
  //
  // The physical byte-stride for a flat-buffer access is coeff * elementBytes
  // (memref indices are in elements, not bytes).
  // We classify based on coeff * elementBytes:
  int64_t byteStride = sym.coeff * elementBytes;

  if (sym.coeff == 0) {
    // Address is loop-invariant.
    cls.kind = AccessKind::Broadcast;
  } else if (byteStride == elementBytes) {
    // Unit stride: advancing by one element per iteration.
    cls.kind = AccessKind::Unit;
    cls.stride = elementBytes;
  } else {
    cls.kind = AccessKind::Strided;
    cls.stride = byteStride;
  }

  return cls;
}

}  // namespace mlir::lego

// ---------------------------------------------------------------------------
// Tier-B speculative-unroll evaluator
// ---------------------------------------------------------------------------
namespace {

// Concrete-evaluation of an integer-arith DAG: given that the value of `iv`
// is fixed at `ivVal`, returns the concrete int64_t result of evaluating
// `root`, or std::nullopt if any node can't be evaluated (e.g. depends on
// non-iv block args, has a non-supported op).
static std::optional<int64_t>
concreteEvaluate(Value root, Value iv, int64_t ivVal,
                 llvm::DenseMap<Value, std::optional<int64_t>> &cache) {
  if (auto it = cache.find(root); it != cache.end()) return it->second;
  std::optional<int64_t> result;

  if (root == iv) {
    result = ivVal;
    cache[root] = result;
    return result;
  }
  Operation *defOp = root.getDefiningOp();
  if (!defOp) {
    // Other block argument — not evaluable.
    cache[root] = std::nullopt;
    return std::nullopt;
  }

  // Constants.
  if (auto cst = dyn_cast<arith::ConstantIndexOp>(defOp)) {
    result = cst.value();
  } else if (auto cst = dyn_cast<arith::ConstantOp>(defOp)) {
    if (auto ia = dyn_cast<IntegerAttr>(cst.getValue())) {
      result = ia.getInt();
    }
  // Binary integer ops.
  } else if (defOp->getNumOperands() == 2 && defOp->getNumResults() == 1) {
    auto a = concreteEvaluate(defOp->getOperand(0), iv, ivVal, cache);
    auto b = concreteEvaluate(defOp->getOperand(1), iv, ivVal, cache);
    if (a && b) {
      if (isa<arith::AddIOp>(defOp))          result = *a + *b;
      else if (isa<arith::SubIOp>(defOp))     result = *a - *b;
      else if (isa<arith::MulIOp>(defOp))     result = *a * *b;
      else if (isa<arith::DivUIOp>(defOp) && *b != 0)
        result = (int64_t)((uint64_t)*a / (uint64_t)*b);
      else if (isa<arith::DivSIOp>(defOp) && *b != 0) result = *a / *b;
      else if (isa<arith::RemUIOp>(defOp) && *b != 0)
        result = (int64_t)((uint64_t)*a % (uint64_t)*b);
      else if (isa<arith::RemSIOp>(defOp) && *b != 0) result = *a % *b;
      else if (isa<arith::ShLIOp>(defOp))     result = *a << *b;
      else if (isa<arith::ShRUIOp>(defOp))
        result = (int64_t)((uint64_t)*a >> *b);
      else if (isa<arith::ShRSIOp>(defOp))    result = *a >> *b;
      else if (isa<arith::AndIOp>(defOp))     result = *a & *b;
      else if (isa<arith::OrIOp>(defOp))      result = *a | *b;
      else if (isa<arith::XOrIOp>(defOp))     result = *a ^ *b;
      // Otherwise: unsupported, leave result as nullopt.
    }
  } else if (isa<arith::IndexCastOp, arith::IndexCastUIOp>(defOp)) {
    result = concreteEvaluate(defOp->getOperand(0), iv, ivVal, cache);
  }
  // (Add more ops as needed — the above covers most LEGO-generated index arithmetic.)

  cache[root] = result;
  return result;
}

}  // anonymous namespace

namespace mlir::lego {

AccessClassification solveAccessTierB(Operation *memrefOp, Value iv,
                                      int64_t elementBytes, int64_t L) {
  AccessClassification cls;
  cls.elementBytes = elementBytes;
  cls.kind = AccessKind::NonAffine;

  // Get the address index value (first index of memref.load/store).
  Value addr;
  if (auto load = dyn_cast<memref::LoadOp>(memrefOp)) {
    if (!load.getIndices().empty()) addr = load.getIndices().front();
  } else if (auto store = dyn_cast<memref::StoreOp>(memrefOp)) {
    if (!store.getIndices().empty()) addr = store.getIndices().front();
  }
  if (!addr) return cls;

  // Probe addr(iv = k) for k = 0..L-1.
  // (For v1, baseline=0: matches the "starting iteration" of the strip-mined
  // loop. The pattern test uses differences, so baseline only shifts all
  // addresses uniformly — it doesn't change classification.)
  llvm::DenseMap<Value, std::optional<int64_t>> cache;
  llvm::SmallVector<int64_t, 16> addrs;
  addrs.reserve(L);
  for (int64_t k = 0; k < L; ++k) {
    cache.clear();
    auto v = concreteEvaluate(addr, iv, /*ivVal=*/k, cache);
    if (!v) return cls;  // NonAffine — can't evaluate.
    addrs.push_back(*v);
  }
  if ((int64_t)addrs.size() < 2) return cls;

  // Compute consecutive differences and check uniformity.
  int64_t firstStep = addrs[1] - addrs[0];
  bool uniform = true;
  int64_t boundary = -1;
  int boundaryCount = 0;
  for (size_t i = 1; i < addrs.size(); ++i) {
    int64_t step = addrs[i] - addrs[i - 1];
    if (step != firstStep) {
      uniform = false;
      if (boundaryCount == 0) boundary = (int64_t)i;
      boundaryCount++;
    }
  }

  if (uniform) {
    if (firstStep == elementBytes) {
      cls.kind = AccessKind::Unit;
      cls.stride = elementBytes;
    } else if (firstStep == 0) {
      cls.kind = AccessKind::Broadcast;
    } else {
      cls.kind = AccessKind::Strided;
      cls.stride = firstStep;
    }
    return cls;
  }

  // Cross-block detection: two contiguous runs of unit stride with one jump.
  if (boundaryCount == 1) {
    // Verify both segments have unit-stride (elementBytes per step).
    bool segmentsUnit = true;
    for (size_t i = 1; i < addrs.size(); ++i) {
      if ((int64_t)i == boundary) continue;  // skip the jump step
      if (addrs[i] - addrs[i - 1] != elementBytes) {
        segmentsUnit = false;
        break;
      }
    }
    if (segmentsUnit) {
      cls.kind = AccessKind::CrossBlock;
      cls.boundary = boundary;
      return cls;
    }
  }

  // Otherwise: NonAffine.
  return cls;
}

}  // namespace mlir::lego

// ---------------------------------------------------------------------------
// Pass implementation
// ---------------------------------------------------------------------------
namespace {

// ---------------------------------------------------------------------------
// Target → register-lane helpers (Task 7)
// ---------------------------------------------------------------------------

// Maps target identifier to vector-register lanes per element of given byte
// width. AVX-512: 64-byte registers. AVX2: 32-byte. NEON: 16-byte.
static int64_t getRegisterLanesForType(llvm::StringRef target,
                                       int64_t elementBytes) {
  if (elementBytes <= 0) return 1;
  if (target == "avx512") return 64 / elementBytes;
  if (target == "avx2")   return 32 / elementBytes;
  if (target == "neon")   return 16 / elementBytes;
  // Conservative default: AVX2.
  return 32 / elementBytes;
}

// Safe lcm for int64_t.  Uses std::gcd to avoid signed-overflow that
// std::lcm can produce on some libstdc++ versions.
static int64_t lcm_i64(int64_t a, int64_t b) {
  if (a == 0 || b == 0) return 0;
  int64_t g = std::gcd(a, b);
  return (a / g) * b;
}

// ---------------------------------------------------------------------------
// Per-loop analysis state
// ---------------------------------------------------------------------------

struct LoopAnalysis {
  scf::ForOp forOp;
  llvm::SmallVector<Operation *, 4> accesses;
  llvm::SmallVector<lego::AccessClassification, 4> classes;
  int64_t L_strip = 1;  // strip-mine factor (Task 7); rewrite lands in Task 8.
  // Future: double score (Task 8).
};

static llvm::SmallVector<LoopAnalysis>
collectCandidateLoops(func::FuncOp func) {
  llvm::SmallVector<LoopAnalysis> result;
  func.walk([&](scf::ForOp forOp) {
    LoopAnalysis a;
    a.forOp = forOp;
    forOp.getBody()->walk([&](Operation *op) {
      if (isa<memref::LoadOp, memref::StoreOp>(op))
        a.accesses.push_back(op);
    });
    if (!a.accesses.empty()) result.push_back(std::move(a));
  });
  return result;
}

// Compute the strip-mine factor L_strip for a single LoopAnalysis.
//
// L_strip = lcm(Ln_access) over all constraining accesses, where:
//   Ln_access = min(R_T, T, Ld)  for Unit accesses.
//   Broadcast accesses are skipped (they don't constrain).
//   Strided / NonAffine / CrossBlock → L_strip = 1 (not vectorizable in v1).
//
// Dep distance Ld is INT64_MAX for now — Task 16 will implement memref base
// distinctness analysis to establish finite Ld where appropriate.
// NOTE: LoopAnalysis is taken by non-const reference because scf::ForOp
// accessors (getLowerBound, getUpperBound, getStep) are non-const in this
// MLIR version.  The function does not mutate `a`.
static int64_t computeStripMineFactor(LoopAnalysis &a,
                                      llvm::StringRef target) {
  // Trip count: extract (upper - lower) / step if all three are
  // arith.constant index; otherwise treat as unbounded.
  int64_t T = std::numeric_limits<int64_t>::max();
  scf::ForOp &forOp = a.forOp;
  if (auto lb = forOp.getLowerBound().getDefiningOp<arith::ConstantIndexOp>())
    if (auto ub =
            forOp.getUpperBound().getDefiningOp<arith::ConstantIndexOp>())
      if (auto st = forOp.getStep().getDefiningOp<arith::ConstantIndexOp>())
        if (st.value() > 0)
          T = (ub.value() - lb.value()) / st.value();

  // Dependence distance — Task 7 placeholder. Task 16 will implement memref
  // base distinctness analysis. For now: assume infinite (no dep).
  int64_t Ld = std::numeric_limits<int64_t>::max();

  int64_t L_strip = 1;
  bool sawConstraining = false;
  for (const auto &cls : a.classes) {
    int64_t R_T = getRegisterLanesForType(target, cls.elementBytes);
    int64_t Ln;
    if (cls.kind == lego::AccessKind::Unit) {
      Ln = std::min({R_T, T, Ld});
      sawConstraining = true;
    } else if (cls.kind == lego::AccessKind::Broadcast) {
      // Doesn't constrain L_strip; skip.
      continue;
    } else if (cls.kind == lego::AccessKind::CrossBlock) {
      // CrossBlock: emission lands in Task 12; use register lanes as L.
      Ln = std::min({R_T, T, Ld});
      sawConstraining = true;
    } else {
      // Strided / NonAffine — not handled in Task 7.
      // Tasks 14-15 will handle gather/strided emission.
      return 1;
    }
    if (Ln <= 1) return 1;
    L_strip = (L_strip == 1) ? Ln : lcm_i64(L_strip, Ln);
  }
  if (!sawConstraining) return 1;  // all Broadcasts — nothing to vectorize.
  return L_strip;
}

// ---------------------------------------------------------------------------
// Task 8: Strip-mining + vector.transfer_read/write emission.
// ---------------------------------------------------------------------------

struct StripMineResult {
  scf::ForOp vecLoop;
  scf::ForOp tailLoop;
};

/// Strip-mines `forOp` by L: produces a vec loop with step*L and a tail loop
/// covering (trip mod L) remaining iterations.  Both loops are inserted
/// before `forOp`; the caller is responsible for erasing `forOp` after
/// populating their bodies.
static StripMineResult stripMineForOp(scf::ForOp forOp, int64_t L,
                                      OpBuilder &builder) {
  Location loc = forOp.getLoc();
  builder.setInsertionPoint(forOp);
  Value lb = forOp.getLowerBound();
  Value ub = forOp.getUpperBound();
  Value origStep = forOp.getStep();

  Value Lval = arith::ConstantIndexOp::create(builder, loc, L);
  Value newStep = arith::MulIOp::create(builder, loc, origStep, Lval);

  // alignedSpan = floor((ub - lb) / newStep) * newStep
  Value extent = arith::SubIOp::create(builder, loc, ub, lb);
  Value q = arith::DivUIOp::create(builder, loc, extent, newStep);
  Value alignedSpan = arith::MulIOp::create(builder, loc, q, newStep);
  Value alignedUb = arith::AddIOp::create(builder, loc, lb, alignedSpan);

  auto vecLoop = scf::ForOp::create(builder, loc, lb, alignedUb, newStep);
  auto tailLoop = scf::ForOp::create(builder, loc, alignedUb, ub, origStep);

  return {vecLoop, tailLoop};
}

/// Populate `vecLoop`'s body.
/// For each memref.load/store in the original body that has unit-stride
/// classification, emit vector.transfer_read / vector.transfer_write.
/// Broadcast loads get cloned as scalar then vector.broadcast.
/// Mixed-precision: when an access has element width < L_strip, emit
/// (L_strip / Ln_access) sub-vector ops at sequential offsets.
static void emitVectorBody(scf::ForOp vecLoop, scf::ForOp origLoop,
                           int64_t L_strip,
                           ArrayRef<Operation *> accesses,
                           ArrayRef<lego::AccessClassification> classes,
                           OpBuilder &builder) {
  Location loc = origLoop.getLoc();
  Value newIv = vecLoop.getInductionVar();
  builder.setInsertionPointToStart(vecLoop.getBody());

  IRMapping mapping;
  mapping.map(origLoop.getInductionVar(), newIv);

  // Hard-coded target (matches Task 7 / Task 8 behaviour).
  llvm::StringRef target = "avx512";

  // Per-access natural lane width.
  auto getLnForAccess = [&](size_t idx) -> int64_t {
    return getRegisterLanesForType(target, classes[idx].elementBytes);
  };

  // Sub-vector tracking: for each original Value, store the list of
  // sub-vectors that cover the L_strip-wide span.  When Ln == L_strip the
  // list has exactly one element (the full-width vector); when Ln < L_strip
  // the list has L_strip/Ln elements at offsets 0, Ln, 2*Ln, …
  DenseMap<Value, SmallVector<Value>> subVectorMap;

  // Helper: return the sub-vector list for an original operand.
  // Falls back to a 1-element list containing the IRMapping result.
  auto getSubsFor = [&](Value origOperand) -> SmallVector<Value> {
    if (auto it = subVectorMap.find(origOperand); it != subVectorMap.end())
      return it->second;
    return {mapping.lookupOrDefault(origOperand)};
  };

  // Helper: build an index Value for (baseIv + j * Ln), or just baseIv if j==0.
  auto makeOffset = [&](Value baseIv, int64_t j, int64_t Ln) -> Value {
    if (j == 0) return baseIv;
    Value addend = arith::ConstantIndexOp::create(builder, loc, j * Ln);
    return arith::AddIOp::create(builder, loc, baseIv, addend);
  };

  // Pre-pass: identify loop-invariant scalar SSA values used in the body and
  // pre-broadcast them.  For mixed-precision we broadcast to the *result*
  // element width; here we only broadcast function-arg scalars that appear
  // directly as operands to arith ops, before any width-changing op.
  // We broadcast to L_strip width so that the arith "catch-all" branch can
  // then slice them down when Ln_result < L_strip.
  DenseMap<Value, Value> broadcastMap;
  auto isOutsideLoop = [&](Value v) {
    Operation *defOp = v.getDefiningOp();
    if (!defOp) {
      if (v == origLoop.getInductionVar()) return false;
      return true;
    }
    return !origLoop->isAncestor(defOp);
  };

  for (Operation &op : origLoop.getBody()->getOperations()) {
    for (Value operand : op.getOperands()) {
      if (!isOutsideLoop(operand)) continue;
      if (broadcastMap.contains(operand)) continue;
      Type t = operand.getType();
      if (!t.isIntOrFloat()) continue;
      // Broadcast to L_strip; arith catch-all will slice if needed.
      auto vecTy = VectorType::get({L_strip}, t);
      Value bc = vector::BroadcastOp::create(builder, loc, vecTy, operand);
      broadcastMap[operand] = bc;
    }
  }
  for (auto &[scalar, vec] : broadcastMap) mapping.map(scalar, vec);

  for (Operation &op : origLoop.getBody()->getOperations()) {
    if (isa<scf::YieldOp>(op))
      continue;  // vecLoop already has its own yield

    // -----------------------------------------------------------------------
    // memref.load
    // -----------------------------------------------------------------------
    if (auto load = dyn_cast<memref::LoadOp>(&op)) {
      auto it = std::find(accesses.begin(), accesses.end(), &op);
      assert(it != accesses.end() && "load not found in accesses");
      size_t idx = it - accesses.begin();
      const auto &cls = classes[idx];

      if (cls.kind == lego::AccessKind::Unit) {
        int64_t Ln = getLnForAccess(idx);
        int64_t numSubOps = L_strip / Ln;
        Type elemTy = load.getType();
        auto vecTy = VectorType::get({Ln}, elemTy);
        Value baseIv = mapping.lookupOrDefault(load.getIndices().front());

        SmallVector<Value> subs;
        subs.reserve(numSubOps);
        for (int64_t j = 0; j < numSubOps; ++j) {
          Value off = makeOffset(baseIv, j, Ln);
          auto subVec = vector::TransferReadOp::create(
              builder, loc, vecTy, load.getMemRef(), ValueRange{off},
              /*padding=*/std::nullopt, /*inBounds=*/ArrayRef<bool>{true});
          subs.push_back(subVec.getVector());
        }
        // If numSubOps == 1, we emitted a single vector at Ln == L_strip.
        // Also map the first sub-vector into IRMapping so that consumers that
        // look up via mapping (e.g. broadcast loads) still work.
        mapping.map(load.getResult(), subs[0]);
        subVectorMap[load.getResult()] = std::move(subs);
      } else if (cls.kind == lego::AccessKind::Broadcast) {
        // Loop-invariant load — clone as scalar then broadcast to L_strip.
        Operation *clonedLoad = builder.clone(*load.getOperation(), mapping);
        Type elemTy = load.getType();
        auto vecTy = VectorType::get({L_strip}, elemTy);
        Value bc = vector::BroadcastOp::create(builder, loc, vecTy,
                                               clonedLoad->getResult(0));
        mapping.map(load.getResult(), bc);
        subVectorMap[load.getResult()] = {bc};
      } else if (cls.kind == lego::AccessKind::CrossBlock) {
        // Two adjacent block reads + vector.shuffle.
        //
        // Cross-block pattern: addr(iv+0..L-1) is unit-stride for the first
        // `boundary` lanes, then jumps to the next block for the remaining
        // (L - boundary) lanes. Synthesise this by:
        //   1. Reading L lanes from block N (starting at addr(0)).
        //   2. Reading L lanes from block N+1 (starting at addr(boundary)).
        //   3. vector.shuffle selects lanes [0..boundary) from blockN and
        //      lanes [0..L-boundary) from blockNp1.
        //
        // v1 restriction: only handle the case where Ln == L_strip.
        // If CrossBlock is combined with mixed-precision (Ln < L_strip),
        // fall through to the scalar-clone fallback.
        int64_t Ln = getLnForAccess(idx);
        if (Ln == L_strip) {
          int64_t boundary = cls.boundary;
          Type elemTy = load.getType();
          auto vecTy = VectorType::get({Ln}, elemTy);
          Value baseIv = mapping.lookupOrDefault(load.getIndices().front());

          // Index for block N+1 base: baseIv + boundary.
          Value boundaryConst =
              arith::ConstantIndexOp::create(builder, loc, boundary);
          Value blockNp1Iv =
              arith::AddIOp::create(builder, loc, baseIv, boundaryConst);

          Value blockN = vector::TransferReadOp::create(
              builder, loc, vecTy, load.getMemRef(), ValueRange{baseIv},
              /*padding=*/std::nullopt,
              /*inBounds=*/ArrayRef<bool>{true});
          Value blockNp1 = vector::TransferReadOp::create(
              builder, loc, vecTy, load.getMemRef(), ValueRange{blockNp1Iv},
              /*padding=*/std::nullopt,
              /*inBounds=*/ArrayRef<bool>{true});

          // Shuffle indices: [0..boundary) from blockN (concatenation indices
          // 0..boundary-1), then [0..L-boundary) from blockNp1 (indices
          // Ln..Ln+(L-boundary)-1 in the concatenation).
          SmallVector<int64_t> shuffleIndices;
          shuffleIndices.reserve(Ln);
          for (int64_t lane = 0; lane < Ln; ++lane) {
            if (lane < boundary)
              shuffleIndices.push_back(lane);
            else
              shuffleIndices.push_back(Ln + (lane - boundary));
          }
          Value shuffled = vector::ShuffleOp::create(builder, loc, blockN,
                                                     blockNp1, shuffleIndices);

          SmallVector<Value> subs = {shuffled};
          subVectorMap[load.getResult()] = std::move(subs);
          mapping.map(load.getResult(), shuffled);
        } else {
          // CrossBlock + mixed precision: too complex for v1 — scalar fallback.
          Operation *cloned = builder.clone(*load.getOperation(), mapping);
          mapping.map(load.getResult(), cloned->getResult(0));
        }
      } else {
        // Shouldn't reach here for vectorizable loops.
        Operation *cloned = builder.clone(*load.getOperation(), mapping);
        mapping.map(load.getResult(), cloned->getResult(0));
      }

    // -----------------------------------------------------------------------
    // memref.store
    // -----------------------------------------------------------------------
    } else if (auto store = dyn_cast<memref::StoreOp>(&op)) {
      auto it = std::find(accesses.begin(), accesses.end(), &op);
      assert(it != accesses.end() && "store not found in accesses");
      size_t idx = it - accesses.begin();
      const auto &cls = classes[idx];

      if (cls.kind == lego::AccessKind::Unit) {
        int64_t Ln = getLnForAccess(idx);
        int64_t numSubOps = L_strip / Ln;
        auto subs = getSubsFor(store.getValue());

        if ((int64_t)subs.size() == numSubOps) {
          Value baseIv = mapping.lookupOrDefault(store.getIndices().front());
          for (int64_t j = 0; j < numSubOps; ++j) {
            Value off = makeOffset(baseIv, j, Ln);
            vector::TransferWriteOp::create(
                builder, loc, subs[j], store.getMemRef(), ValueRange{off},
                /*inBounds=*/ArrayRef<bool>{true});
          }
        } else {
          // Sub-vector count mismatch — scalar fallback.
          builder.clone(*store.getOperation(), mapping);
        }
      } else {
        builder.clone(*store.getOperation(), mapping);
      }

    // -----------------------------------------------------------------------
    // arith (and any other) ops — mixed-precision aware pass-through
    // -----------------------------------------------------------------------
    } else {
      // For ops with no results or non-scalar/float results: clone unchanged.
      if (op.getNumResults() != 1) {
        builder.clone(op, mapping);
        continue;
      }
      Value origResult = op.getResult(0);
      Type resTy = origResult.getType();

      if (!resTy.isIntOrFloat()) {
        // Index, memref, etc. — clone with mapping unchanged.
        Operation *cloned = builder.clone(op, mapping);
        mapping.map(origResult, cloned->getResult(0));
        continue;
      }

      // Determine target sub-width for the result.
      int64_t resBytes = resTy.getIntOrFloatBitWidth() / 8;
      int64_t Ln_result = getRegisterLanesForType(target, resBytes);
      int64_t numSubOpsResult = L_strip / Ln_result;

      // Build per-operand sub-vector lists aligned to Ln_result.
      SmallVector<SmallVector<Value>> operandSubs;
      bool sizingFailed = false;
      for (Value operand : op.getOperands()) {
        auto subs = getSubsFor(operand);
        SmallVector<Value> sized;

        if ((int64_t)subs.size() == numSubOpsResult) {
          // Already the right number of pieces.
          sized = subs;
        } else if (subs.size() == 1) {
          Value v = subs[0];
          auto vecTy = dyn_cast<VectorType>(v.getType());
          if (!vecTy) {
            // Scalar — replicate for all sub-ops.
            for (int64_t j = 0; j < numSubOpsResult; ++j) sized.push_back(v);
          } else {
            int64_t srcW = vecTy.getShape()[0];
            if (srcW == Ln_result) {
              sized.push_back(v);
            } else if (srcW > Ln_result) {
              // Wider vector — slice into Ln_result-wide pieces.
              for (int64_t j = 0; j < numSubOpsResult; ++j) {
                Value piece = vector::ExtractStridedSliceOp::create(
                    builder, loc, v,
                    /*offsets=*/ArrayRef<int64_t>{j * Ln_result},
                    /*sizes=*/ArrayRef<int64_t>{Ln_result},
                    /*strides=*/ArrayRef<int64_t>{1});
                sized.push_back(piece);
              }
            } else {
              // srcW < Ln_result: narrower than result (should not happen in
              // well-formed Tier-A kernels; fall back to scalar clone).
              sizingFailed = true;
              break;
            }
          }
        } else {
          // Multi-piece operand list but wrong count: unsupported in v1.
          sizingFailed = true;
          break;
        }
        operandSubs.push_back(std::move(sized));
      }

      if (sizingFailed) {
        // Conservative fallback: clone scalar.
        Operation *cloned = builder.clone(op, mapping);
        mapping.map(origResult, cloned->getResult(0));
        continue;
      }

      // Emit numSubOpsResult instances of the op, each at sub-vector width.
      Type subResTy = VectorType::get({Ln_result}, resTy);
      SmallVector<Value> resultSubs;
      resultSubs.reserve(numSubOpsResult);
      for (int64_t j = 0; j < numSubOpsResult; ++j) {
        SmallVector<Value> opOperands;
        for (auto &operandList : operandSubs) opOperands.push_back(operandList[j]);
        OperationState state(loc, op.getName());
        state.addOperands(opOperands);
        state.addAttributes(op.getAttrs());
        state.addTypes(subResTy);
        Operation *newOp = builder.create(state);
        resultSubs.push_back(newOp->getResult(0));
      }
      // Map first sub-vector for backward compat with scalar consumers.
      mapping.map(origResult, resultSubs[0]);
      subVectorMap[origResult] = std::move(resultSubs);
    }
  }
}

/// Clone the entire original body verbatim into the tail loop (scalar
/// fallback for the (trip mod L) remaining iterations).
static void emitTailBody(scf::ForOp tailLoop, scf::ForOp origLoop,
                         OpBuilder &builder) {
  builder.setInsertionPointToStart(tailLoop.getBody());
  IRMapping mapping;
  mapping.map(origLoop.getInductionVar(), tailLoop.getInductionVar());
  for (Operation &op : origLoop.getBody()->getOperations()) {
    if (isa<scf::YieldOp>(op))
      continue;
    builder.clone(op, mapping);
  }
}

class LegoVectorizePass
    : public mlir::lego::impl::LegoVectorizePassBase<LegoVectorizePass> {
 public:
  using mlir::lego::impl::LegoVectorizePassBase<
      LegoVectorizePass>::LegoVectorizePassBase;

  void runOnOperation() final {
    func::FuncOp func = getOperation();
    auto loops = collectCandidateLoops(func);

    // Collect which loops to erase after the transform loop (cannot erase
    // while iterating if the list contains nested loops, but Task 8 handles
    // only flat single-level loops that are not nested — safe to erase
    // immediately after body population since we iterated by value).
    llvm::SmallVector<scf::ForOp> toErase;

    for (auto &a : loops) {
      Value iv = a.forOp.getInductionVar();
      a.classes.reserve(a.accesses.size());

      // Task 4 didn't expose a TableGen `target` option (GCC brace-init issue),
      // so we hard-code "avx512" here. When Task 17 adds the
      // LegoX86VectorPipeline, it can override via pipeline options if needed;
      // for the v1 pass-only path, AVX-512 is the default.
      llvm::StringRef target = "avx512";

      for (Operation *op : a.accesses) {
        // Determine elementBytes from the op's element type (default 8 = f64).
        int64_t elemBytes = 8;
        Type t;
        if (auto load = dyn_cast<memref::LoadOp>(op)) t = load.getType();
        else if (auto store = dyn_cast<memref::StoreOp>(op))
          t = store.getValue().getType();
        if (t && t.isIntOrFloat()) elemBytes = t.getIntOrFloatBitWidth() / 8;

        auto cls = lego::solveAccessTierA(op, iv, elemBytes);
        if (cls.kind == lego::AccessKind::NonAffine) {
          // Tier B fallback: speculative unroll at concrete iv values 0..L-1.
          int64_t L_probe = getRegisterLanesForType(target, elemBytes);
          cls = lego::solveAccessTierB(op, iv, elemBytes, L_probe);
        }
        a.classes.push_back(cls);
      }

      a.L_strip = computeStripMineFactor(a, target);

      // Task 8: strip-mine + emit vector.transfer_read/write.
      if (a.L_strip <= 1) continue;

      // Body must contain only memref.load/store, arith ops, and scf.yield.
      // Anything else → skip (future tasks will widen the allowlist).
      bool bodyOK = true;
      for (Operation &op : a.forOp.getBody()->getOperations()) {
        if (isa<memref::LoadOp, memref::StoreOp, scf::YieldOp>(op)) continue;
        if (op.getDialect() &&
            isa<arith::ArithDialect>(op.getDialect())) continue;
        bodyOK = false;
        break;
      }
      if (!bodyOK) continue;

      OpBuilder builder(a.forOp);
      StripMineResult mined = stripMineForOp(a.forOp, a.L_strip, builder);
      emitVectorBody(mined.vecLoop, a.forOp, a.L_strip,
                     a.accesses, a.classes, builder);
      emitTailBody(mined.tailLoop, a.forOp, builder);
      toErase.push_back(a.forOp);
    }

    // Erase original loops after all transforms are complete.
    for (scf::ForOp op : toErase)
      op.erase();
  }
};

}  // namespace

namespace mlir::lego {

std::unique_ptr<Pass> createLegoVectorizePass() {
  return std::make_unique<LegoVectorizePass>();
}

}  // namespace mlir::lego
