//===- LegoVectorize.cpp - Layout-agnostic vectorization pass -------------===//
//
// Lowers loops over Lego-derived arith address expressions to MLIR vector
// dialect ops by symbolic stride analysis. Layout-agnostic: operates on
// post-LegoToArith IR (arith + memref + scf).
//
// Phase B (Tasks 5-10) fills in the actual stride analysis and vectorization
// rewrites. This scaffold registers the pass and leaves IR unchanged.
//
//===----------------------------------------------------------------------===//

#define GEN_PASS_DEF_LEGOVECTORIZEPASS
#include "Lego/Passes.h"

#include "LegoVectorizeUtils.h"

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Pass/Pass.h"

#include <limits>
#include <numeric>  // std::gcd (C++17)

using namespace mlir;

// ---------------------------------------------------------------------------
// Tier-A stride solver implementation
// ---------------------------------------------------------------------------
namespace mlir::lego {

// ---------------------------------------------------------------------------
// Lightweight symbolic integer evaluator.
//
// Represents values as (base_coeff * iv + constant_offset) where:
//   - base_coeff = coefficient of the induction variable
//   - constant   = the constant offset
//   - valid      = false if the expression is non-affine / unknown
//
// This is sufficient for Tier-A: all address expressions generated by
// LegoToArith for 1-D row-major accesses are linear in the loop iv.
// ---------------------------------------------------------------------------
struct AffineVal {
  bool valid = true;     // false → NonAffine (bail out)
  int64_t coeff = 0;     // coefficient of iv
  int64_t constant = 0;  // constant part

  static AffineVal nonAffine() {
    AffineVal v;
    v.valid = false;
    return v;
  }
  static AffineVal constant_val(int64_t c) {
    AffineVal v;
    v.coeff = 0;
    v.constant = c;
    return v;
  }
  static AffineVal iv_val() {
    AffineVal v;
    v.coeff = 1;
    v.constant = 0;
    return v;
  }
};

// Evaluate the index expression `v` symbolically.
// `iv` is the loop induction variable; any other block argument is NonAffine.
// Caches results in `cache` (keyed by Value) to avoid exponential blowup.
static AffineVal evalAffine(Value v, Value iv,
                             llvm::DenseMap<Value, AffineVal> &cache) {
  // Cache hit?
  auto it = cache.find(v);
  if (it != cache.end())
    return it->second;

  AffineVal result;

  // Block argument cases.
  Operation *defOp = v.getDefiningOp();
  if (!defOp) {
    // Block argument: if it's the induction variable, it's iv; otherwise fail.
    result = (v == iv) ? AffineVal::iv_val() : AffineVal::nonAffine();
    cache[v] = result;
    return result;
  }

  // Constant index.
  if (auto cst = dyn_cast<arith::ConstantIndexOp>(defOp)) {
    result = AffineVal::constant_val(cst.value());
    cache[v] = result;
    return result;
  }

  // Generic arith.constant returning index type.
  if (auto cst = dyn_cast<arith::ConstantOp>(defOp)) {
    if (auto iattr = dyn_cast<IntegerAttr>(cst.getValue())) {
      result = AffineVal::constant_val(iattr.getInt());
      cache[v] = result;
      return result;
    }
    result = AffineVal::nonAffine();
    cache[v] = result;
    return result;
  }

  // addi(a, b)  →  (ca+cb)*iv + (ka+kb)
  if (auto add = dyn_cast<arith::AddIOp>(defOp)) {
    auto a = evalAffine(add.getLhs(), iv, cache);
    auto b = evalAffine(add.getRhs(), iv, cache);
    if (!a.valid || !b.valid)
      result = AffineVal::nonAffine();
    else
      result = {true, a.coeff + b.coeff, a.constant + b.constant};
    cache[v] = result;
    return result;
  }

  // subi(a, b)  →  (ca-cb)*iv + (ka-kb)
  if (auto sub = dyn_cast<arith::SubIOp>(defOp)) {
    auto a = evalAffine(sub.getLhs(), iv, cache);
    auto b = evalAffine(sub.getRhs(), iv, cache);
    if (!a.valid || !b.valid)
      result = AffineVal::nonAffine();
    else
      result = {true, a.coeff - b.coeff, a.constant - b.constant};
    cache[v] = result;
    return result;
  }

  // muli(a, constant)  →  ca*constant*iv + ka*constant
  if (auto mul = dyn_cast<arith::MulIOp>(defOp)) {
    auto a = evalAffine(mul.getLhs(), iv, cache);
    auto b = evalAffine(mul.getRhs(), iv, cache);
    if (!a.valid || !b.valid) {
      result = AffineVal::nonAffine();
    } else if (a.coeff == 0) {
      // a is a constant; b may have iv.
      result = {true, a.constant * b.coeff, a.constant * b.constant};
    } else if (b.coeff == 0) {
      // b is a constant; a may have iv.
      result = {true, b.constant * a.coeff, b.constant * a.constant};
    } else {
      // Both have iv → quadratic, not affine.
      result = AffineVal::nonAffine();
    }
    cache[v] = result;
    return result;
  }

  // index_cast (arith.index_cast or arith.index_castui) — treat as identity.
  if (isa<arith::IndexCastOp, arith::IndexCastUIOp>(defOp)) {
    result = evalAffine(defOp->getOperand(0), iv, cache);
    cache[v] = result;
    return result;
  }

  // Anything else → NonAffine.
  result = AffineVal::nonAffine();
  cache[v] = result;
  return result;
}

AccessClassification solveAccessTierA(Operation *memrefOp, Value iv,
                                      int64_t elementBytes) {
  AccessClassification cls;
  cls.elementBytes = elementBytes;

  // Extract the (first) index from a load or store.
  Value addr;
  if (auto load = dyn_cast<memref::LoadOp>(memrefOp)) {
    if (load.getIndices().empty()) return cls;  // scalar — NonAffine
    addr = load.getIndices().front();
  } else if (auto store = dyn_cast<memref::StoreOp>(memrefOp)) {
    if (store.getIndices().empty()) return cls;
    addr = store.getIndices().front();
  } else {
    return cls;
  }

  // Evaluate S(iv) symbolically.
  llvm::DenseMap<Value, AffineVal> cache;
  AffineVal sym = evalAffine(addr, iv, cache);

  if (!sym.valid) {
    cls.kind = AccessKind::NonAffine;
    return cls;
  }

  // The per-step difference is S(iv+1) - S(iv) = coeff (the coefficient of iv).
  // (S(iv+1) = coeff*(iv+1) + constant = coeff*iv + coeff + constant)
  // diff = S(iv+1) - S(iv) = coeff.
  //
  // The physical byte-stride for a flat-buffer access is coeff * elementBytes
  // (memref indices are in elements, not bytes).
  // We classify based on coeff * elementBytes:
  int64_t byteStride = sym.coeff * elementBytes;

  if (sym.coeff == 0) {
    // Address is loop-invariant.
    cls.kind = AccessKind::Broadcast;
  } else if (byteStride == elementBytes) {
    // Unit stride: advancing by one element per iteration.
    cls.kind = AccessKind::Unit;
    cls.stride = elementBytes;
  } else {
    cls.kind = AccessKind::Strided;
    cls.stride = byteStride;
  }

  return cls;
}

}  // namespace mlir::lego

// ---------------------------------------------------------------------------
// Pass implementation
// ---------------------------------------------------------------------------
namespace {

// ---------------------------------------------------------------------------
// Target → register-lane helpers (Task 7)
// ---------------------------------------------------------------------------

// Maps target identifier to vector-register lanes per element of given byte
// width. AVX-512: 64-byte registers. AVX2: 32-byte. NEON: 16-byte.
static int64_t getRegisterLanesForType(llvm::StringRef target,
                                       int64_t elementBytes) {
  if (elementBytes <= 0) return 1;
  if (target == "avx512") return 64 / elementBytes;
  if (target == "avx2")   return 32 / elementBytes;
  if (target == "neon")   return 16 / elementBytes;
  // Conservative default: AVX2.
  return 32 / elementBytes;
}

// Safe lcm for int64_t.  Uses std::gcd to avoid signed-overflow that
// std::lcm can produce on some libstdc++ versions.
static int64_t lcm_i64(int64_t a, int64_t b) {
  if (a == 0 || b == 0) return 0;
  int64_t g = std::gcd(a, b);
  return (a / g) * b;
}

// ---------------------------------------------------------------------------
// Per-loop analysis state
// ---------------------------------------------------------------------------

struct LoopAnalysis {
  scf::ForOp forOp;
  llvm::SmallVector<Operation *, 4> accesses;
  llvm::SmallVector<lego::AccessClassification, 4> classes;
  int64_t L_strip = 1;  // strip-mine factor (Task 7); rewrite lands in Task 8.
  // Future: double score (Task 8).
};

static llvm::SmallVector<LoopAnalysis>
collectCandidateLoops(func::FuncOp func) {
  llvm::SmallVector<LoopAnalysis> result;
  func.walk([&](scf::ForOp forOp) {
    LoopAnalysis a;
    a.forOp = forOp;
    forOp.getBody()->walk([&](Operation *op) {
      if (isa<memref::LoadOp, memref::StoreOp>(op))
        a.accesses.push_back(op);
    });
    if (!a.accesses.empty()) result.push_back(std::move(a));
  });
  return result;
}

// Compute the strip-mine factor L_strip for a single LoopAnalysis.
//
// L_strip = lcm(Ln_access) over all constraining accesses, where:
//   Ln_access = min(R_T, T, Ld)  for Unit accesses.
//   Broadcast accesses are skipped (they don't constrain).
//   Strided / NonAffine / CrossBlock → L_strip = 1 (not vectorizable in v1).
//
// Dep distance Ld is INT64_MAX for now — Task 16 will implement memref base
// distinctness analysis to establish finite Ld where appropriate.
// NOTE: LoopAnalysis is taken by non-const reference because scf::ForOp
// accessors (getLowerBound, getUpperBound, getStep) are non-const in this
// MLIR version.  The function does not mutate `a`.
static int64_t computeStripMineFactor(LoopAnalysis &a,
                                      llvm::StringRef target) {
  // Trip count: extract (upper - lower) / step if all three are
  // arith.constant index; otherwise treat as unbounded.
  int64_t T = std::numeric_limits<int64_t>::max();
  scf::ForOp &forOp = a.forOp;
  if (auto lb = forOp.getLowerBound().getDefiningOp<arith::ConstantIndexOp>())
    if (auto ub =
            forOp.getUpperBound().getDefiningOp<arith::ConstantIndexOp>())
      if (auto st = forOp.getStep().getDefiningOp<arith::ConstantIndexOp>())
        if (st.value() > 0)
          T = (ub.value() - lb.value()) / st.value();

  // Dependence distance — Task 7 placeholder. Task 16 will implement memref
  // base distinctness analysis. For now: assume infinite (no dep).
  int64_t Ld = std::numeric_limits<int64_t>::max();

  int64_t L_strip = 1;
  bool sawConstraining = false;
  for (const auto &cls : a.classes) {
    int64_t R_T = getRegisterLanesForType(target, cls.elementBytes);
    int64_t Ln;
    if (cls.kind == lego::AccessKind::Unit) {
      Ln = std::min({R_T, T, Ld});
      sawConstraining = true;
    } else if (cls.kind == lego::AccessKind::Broadcast) {
      // Doesn't constrain L_strip; skip.
      continue;
    } else {
      // Strided / NonAffine / CrossBlock — not handled in Task 7.
      // Tasks 14-15 will handle gather/strided emission.
      return 1;
    }
    if (Ln <= 1) return 1;
    L_strip = (L_strip == 1) ? Ln : lcm_i64(L_strip, Ln);
  }
  if (!sawConstraining) return 1;  // all Broadcasts — nothing to vectorize.
  return L_strip;
}

class LegoVectorizePass
    : public mlir::lego::impl::LegoVectorizePassBase<LegoVectorizePass> {
 public:
  using mlir::lego::impl::LegoVectorizePassBase<
      LegoVectorizePass>::LegoVectorizePassBase;

  void runOnOperation() final {
    func::FuncOp func = getOperation();
    auto loops = collectCandidateLoops(func);

    for (auto &a : loops) {
      Value iv = a.forOp.getInductionVar();
      a.classes.reserve(a.accesses.size());
      for (Operation *op : a.accesses) {
        // Determine elementBytes from the op's element type (default to 8 for f64).
        int64_t elemBytes = 8;
        Type t;
        if (auto load = dyn_cast<memref::LoadOp>(op)) t = load.getType();
        else if (auto store = dyn_cast<memref::StoreOp>(op))
          t = store.getValue().getType();
        if (t && t.isIntOrFloat()) elemBytes = t.getIntOrFloatBitWidth() / 8;
        a.classes.push_back(lego::solveAccessTierA(op, iv, elemBytes));
      }

      // Task 4 didn't expose a TableGen `target` option (GCC brace-init issue),
      // so we hard-code "avx512" here. When Task 17 adds the
      // LegoX86VectorPipeline, it can override via pipeline options if needed;
      // for the v1 pass-only path, AVX-512 is the default.
      llvm::StringRef target = "avx512";
      a.L_strip = computeStripMineFactor(a, target);
    }

    // Phase-B Task 8-9 will use `loops` for scoring + rewrite.
    // Task 7 stops here — L_strip is computed but IR is not yet mutated.
  }
};

}  // namespace

namespace mlir::lego {

std::unique_ptr<Pass> createLegoVectorizePass() {
  return std::make_unique<LegoVectorizePass>();
}

}  // namespace mlir::lego
