//===- LegoVectorize.cpp - Layout-agnostic vectorization pass -------------===//
//
// Lowers loops over Lego-derived arith address expressions to MLIR vector
// dialect ops by symbolic stride analysis. Layout-agnostic: operates on
// post-LegoToArith IR (arith + memref + scf).
//
// Phase B (Tasks 5-10) fills in the actual stride analysis and vectorization
// rewrites. This scaffold registers the pass and leaves IR unchanged.
//
//===----------------------------------------------------------------------===//

#define GEN_PASS_DEF_LEGOVECTORIZEPASS
#include "Lego/Passes.h"

#include "LegoVectorizeUtils.h"

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Pass/Pass.h"

using namespace mlir;

// ---------------------------------------------------------------------------
// Tier-A stride solver implementation
// ---------------------------------------------------------------------------
namespace mlir::lego {

// ---------------------------------------------------------------------------
// Lightweight symbolic integer evaluator.
//
// Represents values as (base_coeff * iv + constant_offset) where:
//   - base_coeff = coefficient of the induction variable
//   - constant   = the constant offset
//   - valid      = false if the expression is non-affine / unknown
//
// This is sufficient for Tier-A: all address expressions generated by
// LegoToArith for 1-D row-major accesses are linear in the loop iv.
// ---------------------------------------------------------------------------
struct AffineVal {
  bool valid = true;     // false → NonAffine (bail out)
  int64_t coeff = 0;     // coefficient of iv
  int64_t constant = 0;  // constant part

  static AffineVal nonAffine() {
    AffineVal v;
    v.valid = false;
    return v;
  }
  static AffineVal constant_val(int64_t c) {
    AffineVal v;
    v.coeff = 0;
    v.constant = c;
    return v;
  }
  static AffineVal iv_val() {
    AffineVal v;
    v.coeff = 1;
    v.constant = 0;
    return v;
  }
};

// Evaluate the index expression `v` symbolically.
// `iv` is the loop induction variable; any other block argument is NonAffine.
// Caches results in `cache` (keyed by Value) to avoid exponential blowup.
static AffineVal evalAffine(Value v, Value iv,
                             llvm::DenseMap<Value, AffineVal> &cache) {
  // Cache hit?
  auto it = cache.find(v);
  if (it != cache.end())
    return it->second;

  AffineVal result;

  // Block argument cases.
  Operation *defOp = v.getDefiningOp();
  if (!defOp) {
    // Block argument: if it's the induction variable, it's iv; otherwise fail.
    result = (v == iv) ? AffineVal::iv_val() : AffineVal::nonAffine();
    cache[v] = result;
    return result;
  }

  // Constant index.
  if (auto cst = dyn_cast<arith::ConstantIndexOp>(defOp)) {
    result = AffineVal::constant_val(cst.value());
    cache[v] = result;
    return result;
  }

  // Generic arith.constant returning index type.
  if (auto cst = dyn_cast<arith::ConstantOp>(defOp)) {
    if (auto iattr = dyn_cast<IntegerAttr>(cst.getValue())) {
      result = AffineVal::constant_val(iattr.getInt());
      cache[v] = result;
      return result;
    }
    result = AffineVal::nonAffine();
    cache[v] = result;
    return result;
  }

  // addi(a, b)  →  (ca+cb)*iv + (ka+kb)
  if (auto add = dyn_cast<arith::AddIOp>(defOp)) {
    auto a = evalAffine(add.getLhs(), iv, cache);
    auto b = evalAffine(add.getRhs(), iv, cache);
    if (!a.valid || !b.valid)
      result = AffineVal::nonAffine();
    else
      result = {true, a.coeff + b.coeff, a.constant + b.constant};
    cache[v] = result;
    return result;
  }

  // subi(a, b)  →  (ca-cb)*iv + (ka-kb)
  if (auto sub = dyn_cast<arith::SubIOp>(defOp)) {
    auto a = evalAffine(sub.getLhs(), iv, cache);
    auto b = evalAffine(sub.getRhs(), iv, cache);
    if (!a.valid || !b.valid)
      result = AffineVal::nonAffine();
    else
      result = {true, a.coeff - b.coeff, a.constant - b.constant};
    cache[v] = result;
    return result;
  }

  // muli(a, constant)  →  ca*constant*iv + ka*constant
  if (auto mul = dyn_cast<arith::MulIOp>(defOp)) {
    auto a = evalAffine(mul.getLhs(), iv, cache);
    auto b = evalAffine(mul.getRhs(), iv, cache);
    if (!a.valid || !b.valid) {
      result = AffineVal::nonAffine();
    } else if (a.coeff == 0) {
      // a is a constant; b may have iv.
      result = {true, a.constant * b.coeff, a.constant * b.constant};
    } else if (b.coeff == 0) {
      // b is a constant; a may have iv.
      result = {true, b.constant * a.coeff, b.constant * a.constant};
    } else {
      // Both have iv → quadratic, not affine.
      result = AffineVal::nonAffine();
    }
    cache[v] = result;
    return result;
  }

  // index_cast (arith.index_cast or arith.index_castui) — treat as identity.
  if (isa<arith::IndexCastOp, arith::IndexCastUIOp>(defOp)) {
    result = evalAffine(defOp->getOperand(0), iv, cache);
    cache[v] = result;
    return result;
  }

  // Anything else → NonAffine.
  result = AffineVal::nonAffine();
  cache[v] = result;
  return result;
}

AccessClassification solveAccessTierA(Operation *memrefOp, Value iv,
                                      int64_t elementBytes) {
  AccessClassification cls;
  cls.elementBytes = elementBytes;

  // Extract the (first) index from a load or store.
  Value addr;
  if (auto load = dyn_cast<memref::LoadOp>(memrefOp)) {
    if (load.getIndices().empty()) return cls;  // scalar — NonAffine
    addr = load.getIndices().front();
  } else if (auto store = dyn_cast<memref::StoreOp>(memrefOp)) {
    if (store.getIndices().empty()) return cls;
    addr = store.getIndices().front();
  } else {
    return cls;
  }

  // Evaluate S(iv) symbolically.
  llvm::DenseMap<Value, AffineVal> cache;
  AffineVal sym = evalAffine(addr, iv, cache);

  if (!sym.valid) {
    cls.kind = AccessKind::NonAffine;
    return cls;
  }

  // The per-step difference is S(iv+1) - S(iv) = coeff (the coefficient of iv).
  // (S(iv+1) = coeff*(iv+1) + constant = coeff*iv + coeff + constant)
  // diff = S(iv+1) - S(iv) = coeff.
  //
  // The physical byte-stride for a flat-buffer access is coeff * elementBytes
  // (memref indices are in elements, not bytes).
  // We classify based on coeff * elementBytes:
  int64_t byteStride = sym.coeff * elementBytes;

  if (sym.coeff == 0) {
    // Address is loop-invariant.
    cls.kind = AccessKind::Broadcast;
  } else if (byteStride == elementBytes) {
    // Unit stride: advancing by one element per iteration.
    cls.kind = AccessKind::Unit;
    cls.stride = elementBytes;
  } else {
    cls.kind = AccessKind::Strided;
    cls.stride = byteStride;
  }

  return cls;
}

}  // namespace mlir::lego

// ---------------------------------------------------------------------------
// Pass implementation
// ---------------------------------------------------------------------------
namespace {

class LegoVectorizePass
    : public mlir::lego::impl::LegoVectorizePassBase<LegoVectorizePass> {
 public:
  using mlir::lego::impl::LegoVectorizePassBase<
      LegoVectorizePass>::LegoVectorizePassBase;

  void runOnOperation() final {
    func::FuncOp func = getOperation();
    func.walk([&](scf::ForOp forOp) {
      Value iv = forOp.getInductionVar();
      forOp.getBody()->walk([&](Operation *op) {
        if (!isa<memref::LoadOp, memref::StoreOp>(op))
          return;
        // Determine elementBytes from the element type (default 8 for f64).
        int64_t elemBytes = 8;
        Type t;
        if (auto load = dyn_cast<memref::LoadOp>(op))
          t = load.getType();
        else if (auto store = dyn_cast<memref::StoreOp>(op))
          t = store.getValue().getType();
        if (t && t.isIntOrFloat())
          elemBytes = t.getIntOrFloatBitWidth() / 8;
        // Classify (result currently unused — Phase B Task 6 will collect).
        (void)mlir::lego::solveAccessTierA(op, iv, elemBytes);
      });
    });
    // No rewrite yet — pass remains a no-op for IR.
  }
};

}  // namespace

namespace mlir::lego {

std::unique_ptr<Pass> createLegoVectorizePass() {
  return std::make_unique<LegoVectorizePass>();
}

}  // namespace mlir::lego
