"""Rust codegen — LEGO hello world.

Uses LEGO to derive row-major and tiled index expressions, renders them
as Rust code, writes a complete program, compiles with rustc, and runs it.

Requires: module load rust
"""

import os
import subprocess
import tempfile
import sympy as sp

from lego.core import OrderBy, Row
from lego.rust_printer import LEGORustCodePrinter

# ── Symbolic layout evaluation ───────────────────────────────────────────

M, N = sp.symbols('M N', integer=True, positive=True)
i, j = sp.symbols('i j', integer=True, positive=True)
x = sp.Symbol('x', integer=True, positive=True)

L = OrderBy(Row(M, N)).GroupBy([(M, N)])

forward_expr = L.apply(i, j)        # i*N + j
inv_exprs = L.inv(x)                # [floor(x/N), x % N]

# ── Render as Rust ───────────────────────────────────────────────────────

p = LEGORustCodePrinter()
forward_code = p.doprint(forward_expr)
inv_i_code = p.doprint(inv_exprs[0])
inv_j_code = p.doprint(inv_exprs[1])

print(f"LEGO forward (i,j)->flat: {forward_expr}")
print(f"LEGO inverse flat->(i,j): {inv_exprs}")
print(f"Rust forward:  {forward_code}")
print(f"Rust inv[0]:   {inv_i_code}")
print(f"Rust inv[1]:   {inv_j_code}")
print()

# ── Generate complete Rust program ───────────────────────────────────────

rust_src = f"""\
// Auto-generated by LEGO layout algebra
// Layout: Row-major (M, N)
// Forward: (i, j) -> {forward_code}
// Inverse: flat -> ({inv_i_code}, {inv_j_code})

fn row_major_index(i: i64, j: i64, _m: i64, n: i64) -> i64 {{
    {forward_code.replace('M', '_m').replace('N', 'n')}
}}

fn row_major_inverse(x: i64, _m: i64, n: i64) -> (i64, i64) {{
    let i_out = {inv_i_code.replace('x', 'x').replace('N', 'n')};
    let j_out = {inv_j_code.replace('x', 'x').replace('N', 'n')};
    (i_out, j_out)
}}

fn main() {{
    let m: i64 = 4;
    let n: i64 = 8;
    println!("Row-major layout ({{}} x {{}})", m, n);
    println!("{{:<8}} {{:<8}} {{:<8}} {{:<12}} {{:<8}}", "i", "j", "flat", "inv_i", "inv_j");
    println!("{{:-<44}}", "");

    let mut pass = true;
    for i in 0..m {{
        for j in 0..n {{
            let flat = row_major_index(i, j, m, n);
            let (ri, rj) = row_major_inverse(flat, m, n);
            let ok = ri == i && rj == j;
            if !ok {{ pass = false; }}
            println!("{{:<8}} {{:<8}} {{:<8}} {{:<12}} {{:<8}} {{}}", i, j, flat, ri, rj,
                     if ok {{ "OK" }} else {{ "FAIL" }});
        }}
    }}
    if pass {{
        println!("\\nPASS: All roundtrips match");
    }} else {{
        println!("\\nFAIL: Roundtrip mismatch detected");
        std::process::exit(1);
    }}
}}
"""

# ── Compile and run ──────────────────────────────────────────────────────

with tempfile.TemporaryDirectory() as tmp:
    src_path = os.path.join(tmp, "lego_layout.rs")
    bin_path = os.path.join(tmp, "lego_layout")

    with open(src_path, "w") as f:
        f.write(rust_src)

    print("--- Generated Rust source ---")
    print(rust_src)

    print("--- Compiling with rustc ---")
    result = subprocess.run(["rustc", src_path, "-o", bin_path],
                            capture_output=True, text=True)
    if result.returncode != 0:
        print("Compilation failed:")
        print(result.stderr)
        exit(1)
    print("Compilation OK")

    print("\n--- Running ---")
    result = subprocess.run([bin_path], capture_output=True, text=True)
    print(result.stdout)
    if result.returncode != 0:
        print(result.stderr)
        exit(1)
