"""Julia codegen — LEGO hello world.

Uses LEGO to derive row-major index expressions, renders them as Julia,
writes a complete script, and runs it with the julia interpreter.

Requires: module load julia
"""

import os
import subprocess
import tempfile
import sympy as sp

from lego.core import OrderBy, Row
from lego.julia_printer import LEGOJuliaCodePrinter

# ── Symbolic layout evaluation ───────────────────────────────────────────

M, N = sp.symbols('M N', integer=True, positive=True)
i, j = sp.symbols('i j', integer=True, positive=True)
x = sp.Symbol('x', integer=True, positive=True)

L = OrderBy(Row(M, N)).GroupBy([(M, N)])
forward_expr = L.apply(i, j)
inv_exprs = L.inv(x)

p = LEGOJuliaCodePrinter()
forward_code = p.doprint(forward_expr).strip()
inv_i_code = p.doprint(inv_exprs[0]).strip()
inv_j_code = p.doprint(inv_exprs[1]).strip()

print(f"LEGO forward: {forward_expr}  ->  Julia: {forward_code}")
print(f"LEGO inverse: {inv_exprs}")
print()

# ── Generate complete Julia script ───────────────────────────────────────

julia_src = f"""\
# Auto-generated by LEGO layout algebra
# Layout: Row-major (M, N)
using Printf

function row_major_index(i::Int, j::Int, M::Int, N::Int)::Int
    return {forward_code}
end

function row_major_inverse(x::Int, M::Int, N::Int)::Tuple{{Int, Int}}
    i_out = {inv_i_code}
    j_out = {inv_j_code}
    return (i_out, j_out)
end

function main()
    M, N = 4, 8
    println("Row-major layout ($(M) x $(N))")
    @printf("%-8s %-8s %-8s %-12s %-8s\\n", "i", "j", "flat", "inv_i", "inv_j")
    println(repeat("-", 44))

    pass_all = true
    for i in 0:(M-1)
        for j in 0:(N-1)
            flat = row_major_index(i, j, M, N)
            ri, rj = row_major_inverse(flat, M, N)
            ok = (ri == i && rj == j)
            if !ok
                pass_all = false
            end
            status = ok ? "OK" : "FAIL"
            @printf("%-8d %-8d %-8d %-12d %-8d %s\\n", i, j, flat, ri, rj, status)
        end
    end

    if pass_all
        println("\\nPASS: All roundtrips match")
    else
        println("\\nFAIL: Roundtrip mismatch detected")
        exit(1)
    end
end

main()
"""

# ── Run ──────────────────────────────────────────────────────────────────

with tempfile.TemporaryDirectory() as tmp:
    src_path = os.path.join(tmp, "lego_layout.jl")

    with open(src_path, "w") as f:
        f.write(julia_src)

    print("--- Generated Julia source ---")
    print(julia_src)

    print("--- Running with julia ---")
    result = subprocess.run(["julia", src_path], capture_output=True, text=True)
    print(result.stdout)
    if result.returncode != 0:
        print(result.stderr)
        exit(1)
