"""pytest configuration: stub missing MLIR C-extension bindings.

When the MLIR shared library has not been compiled (e.g. pure-Python dev
environments or CI without the full LLVM build), ``lego.mlir.*`` modules are
absent.  The printer unit tests don't actually call any MLIR APIs — they only
need the module chain to import cleanly.  This conftest:

1. Registers a MetaPathFinder that stubs any ``lego.mlir.*`` import.
2. Pre-injects ``lego.backend.dialects.lego_dialect`` into ``sys.modules``
   with stub attributes so that ``symbolic.py`` can import op classes without
   the compiled MLIR bindings.
"""

import sys
import types
from importlib.abc import MetaPathFinder, Loader
from importlib.machinery import ModuleSpec


class _StubMeta(type):
    """Metaclass making _StubType usable as a base class and callable."""
    def __getattr__(cls, name):
        return _StubType

    def __call__(cls, *a, **kw):
        return object.__new__(cls)

    def __iter__(cls):
        return iter([])


class _StubType(metaclass=_StubMeta):
    """Universal placeholder for any MLIR type, function, or constant.

    Supports:
    - attribute access (returns _StubType),
    - subclassing (via __init_subclass__ passthrough),
    - calling (as a decorator: returns the decorated class unchanged),
    - iteration (yields nothing),
    - indexing (returns _StubType),
    - context-manager protocol.
    """

    def __init_subclass__(cls, **kw):
        pass  # allow arbitrary subclassing

    def __call__(self, *a, **kw):
        # When used as a class decorator, return the class unchanged.
        if len(a) == 1 and isinstance(a[0], type):
            return a[0]
        return _StubType()

    def __iter__(self):
        return iter([])

    def __getattr__(self, name):
        return _StubType

    def __setattr__(self, name, value):
        pass  # silently ignore all attribute sets on stub instances

    def __getitem__(self, item):
        return _StubType

    def __enter__(self):
        return self

    def __exit__(self, *a):
        pass

    def __repr__(self):
        return "<MLIRStub>"


class _StubLoader(Loader):
    def create_module(self, spec):
        return None

    def exec_module(self, module):
        """Populate stub module with catch-all attribute factory."""
        module._cext = _StubType()
        module.ir = _StubType()
        # __all__ must be a list of str; empty list prevents TypeError on
        # ``from lego.mlir.dialects._ods_common import *``.
        module.__all__ = []

        def _getattr(name):
            return _StubType

        module.__getattr__ = _getattr


class _MLIRStubFinder(MetaPathFinder):
    """Intercept any ``lego.mlir`` or ``lego.mlir.*`` import → stub module."""

    def find_spec(self, fullname, path, target=None):
        if fullname == "lego.mlir" or fullname.startswith("lego.mlir."):
            return ModuleSpec(fullname, _StubLoader())
        return None


# ── 1. Register MLIR stub finder early ────────────────────────────────────
sys.meta_path.insert(0, _MLIRStubFinder())


# ── 2. Pre-inject lego.backend.dialects.lego_dialect ──────────────────────
# symbolic.py does a bare ``from lego.backend.dialects.lego_dialect import
# (ApplyOp, ApplyInverseOp, ...)`` which fails when the autogenerated
# _lego_ops_gen.py raises a non-ImportError during its class bodies.
# Pre-registering a stub module prevents that import from ever running the
# real file.
class _FakeLegoDialect(types.ModuleType):
    def __getattr__(self, name):
        return _StubType


_fake_lego_dialect = _FakeLegoDialect("lego.backend.dialects.lego_dialect")
sys.modules["lego.backend.dialects.lego_dialect"] = _fake_lego_dialect
