"""Host-side dispatch templates for GPU shader targets.

Generates minimal host code templates (WebGPU JS, Vulkan C) alongside
compiled shaders so users have a starting point for running the kernels.
"""

from typing import Optional


def webgpu_js_template(
    wgsl_path: str,
    num_buffers: int = 2,
    buffer_size: int = 256,
    workgroup_size: int = 64,
) -> str:
    """Generate a WebGPU JavaScript template for running the compiled WGSL kernel."""
    buffer_entries = []
    bind_entries = []
    for i in range(num_buffers):
        buffer_entries.append(
            f"  const buf{i} = device.createBuffer({{\n"
            f"    size: {buffer_size} * 4,\n"
            f"    usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_SRC | GPUBufferUsage.COPY_DST,\n"
            f"  }});"
        )
        bind_entries.append(
            f"    {{ binding: {i}, resource: {{ buffer: buf{i} }} }},"
        )

    grid = (buffer_size + workgroup_size - 1) // workgroup_size

    return f"""\
// WebGPU host code template for LEGO-compiled kernel
// Generated by lego.backend.host_templates — customize as needed.

async function main() {{
  const adapter = await navigator.gpu.requestAdapter();
  const device = await adapter.requestDevice();

  // Load the WGSL shader
  const shaderCode = await fetch('{wgsl_path}').then(r => r.text());
  const shaderModule = device.createShaderModule({{ code: shaderCode }});

  // Create buffers
{chr(10).join(buffer_entries)}

  // Create bind group layout and pipeline
  const pipeline = device.createComputePipeline({{
    layout: 'auto',
    compute: {{ module: shaderModule }},
  }});

  const bindGroup = device.createBindGroup({{
    layout: pipeline.getBindGroupLayout(0),
    entries: [
{chr(10).join(bind_entries)}
    ],
  }});

  // Dispatch
  const encoder = device.createCommandEncoder();
  const pass = encoder.beginComputePass();
  pass.setPipeline(pipeline);
  pass.setBindGroup(0, bindGroup);
  pass.dispatchWorkgroups({grid});
  pass.end();
  device.queue.submit([encoder.finish()]);

  // Read back results
  const readBuf = device.createBuffer({{
    size: {buffer_size} * 4,
    usage: GPUBufferUsage.MAP_READ | GPUBufferUsage.COPY_DST,
  }});
  const encoder2 = device.createCommandEncoder();
  encoder2.copyBufferToBuffer(buf{num_buffers - 1}, 0, readBuf, 0, {buffer_size} * 4);
  device.queue.submit([encoder2.finish()]);
  await readBuf.mapAsync(GPUMapMode.READ);
  const result = new Float32Array(readBuf.getMappedRange());
  console.log('Result:', result.slice(0, 10));
  readBuf.unmap();
}}

main();
"""


def vulkan_c_template(
    spv_path: str,
    num_buffers: int = 2,
    buffer_size: int = 256,
    workgroup_size: int = 64,
) -> str:
    """Generate a minimal Vulkan C template for running the compiled SPIR-V kernel."""
    grid = (buffer_size + workgroup_size - 1) // workgroup_size

    return f"""\
// Vulkan compute dispatch template for LEGO-compiled kernel
// Generated by lego.backend.host_templates — customize as needed.
// Requires Vulkan SDK. Compile with: gcc -o run_kernel run_kernel.c -lvulkan

#include <vulkan/vulkan.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define BUFFER_SIZE {buffer_size}
#define NUM_BUFFERS {num_buffers}
#define WORKGROUP_SIZE {workgroup_size}
#define GRID_SIZE {grid}
#define SPV_PATH "{spv_path}"

// Load SPIR-V binary from file
static uint32_t* load_spirv(const char* path, size_t* size) {{
    FILE* f = fopen(path, "rb");
    if (!f) {{ fprintf(stderr, "Failed to open %s\\n", path); exit(1); }}
    fseek(f, 0, SEEK_END);
    *size = ftell(f);
    fseek(f, 0, SEEK_SET);
    uint32_t* data = (uint32_t*)malloc(*size);
    fread(data, 1, *size, f);
    fclose(f);
    return data;
}}

int main() {{
    // TODO: Initialize Vulkan instance, device, queue
    // TODO: Create compute pipeline from SPV_PATH
    // TODO: Allocate {num_buffers} storage buffers of {buffer_size} * sizeof(float)
    // TODO: Create descriptor set with buffer bindings
    // TODO: Record command buffer with vkCmdDispatch({grid}, 1, 1)
    // TODO: Submit and read back results

    printf("Vulkan dispatch template for LEGO kernel\\n");
    printf("SPIR-V: %s\\n", SPV_PATH);
    printf("Buffers: %d x %d floats\\n", NUM_BUFFERS, BUFFER_SIZE);
    printf("Dispatch: %d workgroups x %d threads\\n", GRID_SIZE, WORKGROUP_SIZE);
    return 0;
}}
"""


def generate_host_template(
    result,
    output_dir: Optional[str] = None,
) -> str:
    """Generate a host dispatch template for a CompileResult.

    Returns the path to the generated template file.
    """
    import os
    from pathlib import Path

    if output_dir is None:
        output_dir = str(Path(result.kernel_path).parent)

    target = result.target
    name = Path(result.kernel_path).stem

    if target == "webgpu":
        template = webgpu_js_template(
            wgsl_path=Path(result.kernel_path).name,
        )
        out = os.path.join(output_dir, f"{name}_host.js")
    elif target in ("vulkan", "metal", "webgl"):
        template = vulkan_c_template(
            spv_path=result.spv_path or result.kernel_path,
        )
        out = os.path.join(output_dir, f"{name}_host.c")
    else:
        raise ValueError(f"No host template for target '{target}'")

    with open(out, "w") as f:
        f.write(template)
    return out
